version: "2"

run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - errcheck        # Check for unchecked errors
    - govet           # Go vet checks
    - ineffassign     # Detect ineffectual assignments
    - staticcheck     # Static analysis (includes gosimple in v2)
    - unused          # Check for unused code
    - misspell        # Check for spelling errors
    - revive          # Fast, configurable linter
    - goprintffuncname # Check printf-like function names
    - nolintlint      # Check nolint directives
  settings:
    errcheck:
      check-blank: false
      check-type-assertions: false
    govet:
      disable:
        - shadow
    staticcheck:
      checks: ["all"]
  exclusions:
    paths:
      - ent/           # Exclude generated Ent code
      - proto/         # Exclude generated protobuf code
      - github.com/    # Exclude vendored/copied code
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          - errcheck
      # Exclude migration files from certain checks
      - path: pkg/database/migrations/
        linters:
          - revive
          - staticcheck
      # Allow common package names 'api' and 'util'
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"

formatters:
  enable:
    - gofmt          # Format code
    - goimports      # Fix imports
  exclusions:
    paths:
      - ent/           # Exclude generated Ent code
      - proto/         # Exclude generated protobuf code
      - github.com/    # Exclude vendored/copied code

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
  sort-order:
    - linter
    - file
