// Code generated by ent, DO NOT EDIT.

package chat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Chat {
	return predicate.Chat(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Chat {
	return predicate.Chat(sql.FieldContainsFold(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldSessionID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldCreatedBy, v))
}

// ChainID applies equality check predicate on the "chain_id" field. It's identical to ChainIDEQ.
func ChainID(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldChainID, v))
}

// PodID applies equality check predicate on the "pod_id" field. It's identical to PodIDEQ.
func PodID(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldPodID, v))
}

// LastInteractionAt applies equality check predicate on the "last_interaction_at" field. It's identical to LastInteractionAtEQ.
func LastInteractionAt(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldLastInteractionAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContainsFold(FieldSessionID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Chat {
	return predicate.Chat(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Chat {
	return predicate.Chat(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContainsFold(FieldCreatedBy, v))
}

// ChainIDEQ applies the EQ predicate on the "chain_id" field.
func ChainIDEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldChainID, v))
}

// ChainIDNEQ applies the NEQ predicate on the "chain_id" field.
func ChainIDNEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldChainID, v))
}

// ChainIDIn applies the In predicate on the "chain_id" field.
func ChainIDIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldChainID, vs...))
}

// ChainIDNotIn applies the NotIn predicate on the "chain_id" field.
func ChainIDNotIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldChainID, vs...))
}

// ChainIDGT applies the GT predicate on the "chain_id" field.
func ChainIDGT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldChainID, v))
}

// ChainIDGTE applies the GTE predicate on the "chain_id" field.
func ChainIDGTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldChainID, v))
}

// ChainIDLT applies the LT predicate on the "chain_id" field.
func ChainIDLT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldChainID, v))
}

// ChainIDLTE applies the LTE predicate on the "chain_id" field.
func ChainIDLTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldChainID, v))
}

// ChainIDContains applies the Contains predicate on the "chain_id" field.
func ChainIDContains(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContains(FieldChainID, v))
}

// ChainIDHasPrefix applies the HasPrefix predicate on the "chain_id" field.
func ChainIDHasPrefix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasPrefix(FieldChainID, v))
}

// ChainIDHasSuffix applies the HasSuffix predicate on the "chain_id" field.
func ChainIDHasSuffix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasSuffix(FieldChainID, v))
}

// ChainIDEqualFold applies the EqualFold predicate on the "chain_id" field.
func ChainIDEqualFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEqualFold(FieldChainID, v))
}

// ChainIDContainsFold applies the ContainsFold predicate on the "chain_id" field.
func ChainIDContainsFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContainsFold(FieldChainID, v))
}

// PodIDEQ applies the EQ predicate on the "pod_id" field.
func PodIDEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldPodID, v))
}

// PodIDNEQ applies the NEQ predicate on the "pod_id" field.
func PodIDNEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldPodID, v))
}

// PodIDIn applies the In predicate on the "pod_id" field.
func PodIDIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldPodID, vs...))
}

// PodIDNotIn applies the NotIn predicate on the "pod_id" field.
func PodIDNotIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldPodID, vs...))
}

// PodIDGT applies the GT predicate on the "pod_id" field.
func PodIDGT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldPodID, v))
}

// PodIDGTE applies the GTE predicate on the "pod_id" field.
func PodIDGTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldPodID, v))
}

// PodIDLT applies the LT predicate on the "pod_id" field.
func PodIDLT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldPodID, v))
}

// PodIDLTE applies the LTE predicate on the "pod_id" field.
func PodIDLTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldPodID, v))
}

// PodIDContains applies the Contains predicate on the "pod_id" field.
func PodIDContains(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContains(FieldPodID, v))
}

// PodIDHasPrefix applies the HasPrefix predicate on the "pod_id" field.
func PodIDHasPrefix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasPrefix(FieldPodID, v))
}

// PodIDHasSuffix applies the HasSuffix predicate on the "pod_id" field.
func PodIDHasSuffix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasSuffix(FieldPodID, v))
}

// PodIDIsNil applies the IsNil predicate on the "pod_id" field.
func PodIDIsNil() predicate.Chat {
	return predicate.Chat(sql.FieldIsNull(FieldPodID))
}

// PodIDNotNil applies the NotNil predicate on the "pod_id" field.
func PodIDNotNil() predicate.Chat {
	return predicate.Chat(sql.FieldNotNull(FieldPodID))
}

// PodIDEqualFold applies the EqualFold predicate on the "pod_id" field.
func PodIDEqualFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEqualFold(FieldPodID, v))
}

// PodIDContainsFold applies the ContainsFold predicate on the "pod_id" field.
func PodIDContainsFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContainsFold(FieldPodID, v))
}

// LastInteractionAtEQ applies the EQ predicate on the "last_interaction_at" field.
func LastInteractionAtEQ(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldLastInteractionAt, v))
}

// LastInteractionAtNEQ applies the NEQ predicate on the "last_interaction_at" field.
func LastInteractionAtNEQ(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldLastInteractionAt, v))
}

// LastInteractionAtIn applies the In predicate on the "last_interaction_at" field.
func LastInteractionAtIn(vs ...time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldLastInteractionAt, vs...))
}

// LastInteractionAtNotIn applies the NotIn predicate on the "last_interaction_at" field.
func LastInteractionAtNotIn(vs ...time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldLastInteractionAt, vs...))
}

// LastInteractionAtGT applies the GT predicate on the "last_interaction_at" field.
func LastInteractionAtGT(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldLastInteractionAt, v))
}

// LastInteractionAtGTE applies the GTE predicate on the "last_interaction_at" field.
func LastInteractionAtGTE(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldLastInteractionAt, v))
}

// LastInteractionAtLT applies the LT predicate on the "last_interaction_at" field.
func LastInteractionAtLT(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldLastInteractionAt, v))
}

// LastInteractionAtLTE applies the LTE predicate on the "last_interaction_at" field.
func LastInteractionAtLTE(v time.Time) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldLastInteractionAt, v))
}

// LastInteractionAtIsNil applies the IsNil predicate on the "last_interaction_at" field.
func LastInteractionAtIsNil() predicate.Chat {
	return predicate.Chat(sql.FieldIsNull(FieldLastInteractionAt))
}

// LastInteractionAtNotNil applies the NotNil predicate on the "last_interaction_at" field.
func LastInteractionAtNotNil() predicate.Chat {
	return predicate.Chat(sql.FieldNotNull(FieldLastInteractionAt))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.Chat {
	return predicate.Chat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.AlertSession) predicate.Chat {
	return predicate.Chat(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserMessages applies the HasEdge predicate on the "user_messages" edge.
func HasUserMessages() predicate.Chat {
	return predicate.Chat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserMessagesTable, UserMessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserMessagesWith applies the HasEdge predicate on the "user_messages" edge with a given conditions (other predicates).
func HasUserMessagesWith(preds ...predicate.ChatUserMessage) predicate.Chat {
	return predicate.Chat(func(s *sql.Selector) {
		step := newUserMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStages applies the HasEdge predicate on the "stages" edge.
func HasStages() predicate.Chat {
	return predicate.Chat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StagesTable, StagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStagesWith applies the HasEdge predicate on the "stages" edge with a given conditions (other predicates).
func HasStagesWith(preds ...predicate.Stage) predicate.Chat {
	return predicate.Chat(func(s *sql.Selector) {
		step := newStagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Chat) predicate.Chat {
	return predicate.Chat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Chat) predicate.Chat {
	return predicate.Chat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Chat) predicate.Chat {
	return predicate.Chat(sql.NotPredicates(p))
}
