// Code generated by ent, DO NOT EDIT.

package mcpinteraction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContainsFold(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldSessionID, v))
}

// StageID applies equality check predicate on the "stage_id" field. It's identical to StageIDEQ.
func StageID(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldStageID, v))
}

// ExecutionID applies equality check predicate on the "execution_id" field. It's identical to ExecutionIDEQ.
func ExecutionID(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldExecutionID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldCreatedAt, v))
}

// ServerName applies equality check predicate on the "server_name" field. It's identical to ServerNameEQ.
func ServerName(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldServerName, v))
}

// ToolName applies equality check predicate on the "tool_name" field. It's identical to ToolNameEQ.
func ToolName(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldToolName, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldDurationMs, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldErrorMessage, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContainsFold(FieldSessionID, v))
}

// StageIDEQ applies the EQ predicate on the "stage_id" field.
func StageIDEQ(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldStageID, v))
}

// StageIDNEQ applies the NEQ predicate on the "stage_id" field.
func StageIDNEQ(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNEQ(FieldStageID, v))
}

// StageIDIn applies the In predicate on the "stage_id" field.
func StageIDIn(vs ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIn(FieldStageID, vs...))
}

// StageIDNotIn applies the NotIn predicate on the "stage_id" field.
func StageIDNotIn(vs ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotIn(FieldStageID, vs...))
}

// StageIDGT applies the GT predicate on the "stage_id" field.
func StageIDGT(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGT(FieldStageID, v))
}

// StageIDGTE applies the GTE predicate on the "stage_id" field.
func StageIDGTE(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGTE(FieldStageID, v))
}

// StageIDLT applies the LT predicate on the "stage_id" field.
func StageIDLT(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLT(FieldStageID, v))
}

// StageIDLTE applies the LTE predicate on the "stage_id" field.
func StageIDLTE(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLTE(FieldStageID, v))
}

// StageIDContains applies the Contains predicate on the "stage_id" field.
func StageIDContains(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContains(FieldStageID, v))
}

// StageIDHasPrefix applies the HasPrefix predicate on the "stage_id" field.
func StageIDHasPrefix(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldHasPrefix(FieldStageID, v))
}

// StageIDHasSuffix applies the HasSuffix predicate on the "stage_id" field.
func StageIDHasSuffix(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldHasSuffix(FieldStageID, v))
}

// StageIDEqualFold applies the EqualFold predicate on the "stage_id" field.
func StageIDEqualFold(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEqualFold(FieldStageID, v))
}

// StageIDContainsFold applies the ContainsFold predicate on the "stage_id" field.
func StageIDContainsFold(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContainsFold(FieldStageID, v))
}

// ExecutionIDEQ applies the EQ predicate on the "execution_id" field.
func ExecutionIDEQ(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldExecutionID, v))
}

// ExecutionIDNEQ applies the NEQ predicate on the "execution_id" field.
func ExecutionIDNEQ(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNEQ(FieldExecutionID, v))
}

// ExecutionIDIn applies the In predicate on the "execution_id" field.
func ExecutionIDIn(vs ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIn(FieldExecutionID, vs...))
}

// ExecutionIDNotIn applies the NotIn predicate on the "execution_id" field.
func ExecutionIDNotIn(vs ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotIn(FieldExecutionID, vs...))
}

// ExecutionIDGT applies the GT predicate on the "execution_id" field.
func ExecutionIDGT(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGT(FieldExecutionID, v))
}

// ExecutionIDGTE applies the GTE predicate on the "execution_id" field.
func ExecutionIDGTE(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGTE(FieldExecutionID, v))
}

// ExecutionIDLT applies the LT predicate on the "execution_id" field.
func ExecutionIDLT(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLT(FieldExecutionID, v))
}

// ExecutionIDLTE applies the LTE predicate on the "execution_id" field.
func ExecutionIDLTE(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLTE(FieldExecutionID, v))
}

// ExecutionIDContains applies the Contains predicate on the "execution_id" field.
func ExecutionIDContains(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContains(FieldExecutionID, v))
}

// ExecutionIDHasPrefix applies the HasPrefix predicate on the "execution_id" field.
func ExecutionIDHasPrefix(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldHasPrefix(FieldExecutionID, v))
}

// ExecutionIDHasSuffix applies the HasSuffix predicate on the "execution_id" field.
func ExecutionIDHasSuffix(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldHasSuffix(FieldExecutionID, v))
}

// ExecutionIDEqualFold applies the EqualFold predicate on the "execution_id" field.
func ExecutionIDEqualFold(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEqualFold(FieldExecutionID, v))
}

// ExecutionIDContainsFold applies the ContainsFold predicate on the "execution_id" field.
func ExecutionIDContainsFold(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContainsFold(FieldExecutionID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLTE(FieldCreatedAt, v))
}

// InteractionTypeEQ applies the EQ predicate on the "interaction_type" field.
func InteractionTypeEQ(v InteractionType) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldInteractionType, v))
}

// InteractionTypeNEQ applies the NEQ predicate on the "interaction_type" field.
func InteractionTypeNEQ(v InteractionType) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNEQ(FieldInteractionType, v))
}

// InteractionTypeIn applies the In predicate on the "interaction_type" field.
func InteractionTypeIn(vs ...InteractionType) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIn(FieldInteractionType, vs...))
}

// InteractionTypeNotIn applies the NotIn predicate on the "interaction_type" field.
func InteractionTypeNotIn(vs ...InteractionType) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotIn(FieldInteractionType, vs...))
}

// ServerNameEQ applies the EQ predicate on the "server_name" field.
func ServerNameEQ(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldServerName, v))
}

// ServerNameNEQ applies the NEQ predicate on the "server_name" field.
func ServerNameNEQ(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNEQ(FieldServerName, v))
}

// ServerNameIn applies the In predicate on the "server_name" field.
func ServerNameIn(vs ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIn(FieldServerName, vs...))
}

// ServerNameNotIn applies the NotIn predicate on the "server_name" field.
func ServerNameNotIn(vs ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotIn(FieldServerName, vs...))
}

// ServerNameGT applies the GT predicate on the "server_name" field.
func ServerNameGT(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGT(FieldServerName, v))
}

// ServerNameGTE applies the GTE predicate on the "server_name" field.
func ServerNameGTE(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGTE(FieldServerName, v))
}

// ServerNameLT applies the LT predicate on the "server_name" field.
func ServerNameLT(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLT(FieldServerName, v))
}

// ServerNameLTE applies the LTE predicate on the "server_name" field.
func ServerNameLTE(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLTE(FieldServerName, v))
}

// ServerNameContains applies the Contains predicate on the "server_name" field.
func ServerNameContains(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContains(FieldServerName, v))
}

// ServerNameHasPrefix applies the HasPrefix predicate on the "server_name" field.
func ServerNameHasPrefix(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldHasPrefix(FieldServerName, v))
}

// ServerNameHasSuffix applies the HasSuffix predicate on the "server_name" field.
func ServerNameHasSuffix(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldHasSuffix(FieldServerName, v))
}

// ServerNameEqualFold applies the EqualFold predicate on the "server_name" field.
func ServerNameEqualFold(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEqualFold(FieldServerName, v))
}

// ServerNameContainsFold applies the ContainsFold predicate on the "server_name" field.
func ServerNameContainsFold(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContainsFold(FieldServerName, v))
}

// ToolNameEQ applies the EQ predicate on the "tool_name" field.
func ToolNameEQ(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldToolName, v))
}

// ToolNameNEQ applies the NEQ predicate on the "tool_name" field.
func ToolNameNEQ(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNEQ(FieldToolName, v))
}

// ToolNameIn applies the In predicate on the "tool_name" field.
func ToolNameIn(vs ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIn(FieldToolName, vs...))
}

// ToolNameNotIn applies the NotIn predicate on the "tool_name" field.
func ToolNameNotIn(vs ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotIn(FieldToolName, vs...))
}

// ToolNameGT applies the GT predicate on the "tool_name" field.
func ToolNameGT(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGT(FieldToolName, v))
}

// ToolNameGTE applies the GTE predicate on the "tool_name" field.
func ToolNameGTE(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGTE(FieldToolName, v))
}

// ToolNameLT applies the LT predicate on the "tool_name" field.
func ToolNameLT(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLT(FieldToolName, v))
}

// ToolNameLTE applies the LTE predicate on the "tool_name" field.
func ToolNameLTE(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLTE(FieldToolName, v))
}

// ToolNameContains applies the Contains predicate on the "tool_name" field.
func ToolNameContains(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContains(FieldToolName, v))
}

// ToolNameHasPrefix applies the HasPrefix predicate on the "tool_name" field.
func ToolNameHasPrefix(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldHasPrefix(FieldToolName, v))
}

// ToolNameHasSuffix applies the HasSuffix predicate on the "tool_name" field.
func ToolNameHasSuffix(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldHasSuffix(FieldToolName, v))
}

// ToolNameIsNil applies the IsNil predicate on the "tool_name" field.
func ToolNameIsNil() predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIsNull(FieldToolName))
}

// ToolNameNotNil applies the NotNil predicate on the "tool_name" field.
func ToolNameNotNil() predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotNull(FieldToolName))
}

// ToolNameEqualFold applies the EqualFold predicate on the "tool_name" field.
func ToolNameEqualFold(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEqualFold(FieldToolName, v))
}

// ToolNameContainsFold applies the ContainsFold predicate on the "tool_name" field.
func ToolNameContainsFold(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContainsFold(FieldToolName, v))
}

// ToolArgumentsIsNil applies the IsNil predicate on the "tool_arguments" field.
func ToolArgumentsIsNil() predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIsNull(FieldToolArguments))
}

// ToolArgumentsNotNil applies the NotNil predicate on the "tool_arguments" field.
func ToolArgumentsNotNil() predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotNull(FieldToolArguments))
}

// ToolResultIsNil applies the IsNil predicate on the "tool_result" field.
func ToolResultIsNil() predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIsNull(FieldToolResult))
}

// ToolResultNotNil applies the NotNil predicate on the "tool_result" field.
func ToolResultNotNil() predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotNull(FieldToolResult))
}

// AvailableToolsIsNil applies the IsNil predicate on the "available_tools" field.
func AvailableToolsIsNil() predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIsNull(FieldAvailableTools))
}

// AvailableToolsNotNil applies the NotNil predicate on the "available_tools" field.
func AvailableToolsNotNil() predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotNull(FieldAvailableTools))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotNull(FieldDurationMs))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.FieldContainsFold(FieldErrorMessage, v))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.MCPInteraction {
	return predicate.MCPInteraction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.AlertSession) predicate.MCPInteraction {
	return predicate.MCPInteraction(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStage applies the HasEdge predicate on the "stage" edge.
func HasStage() predicate.MCPInteraction {
	return predicate.MCPInteraction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StageTable, StageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStageWith applies the HasEdge predicate on the "stage" edge with a given conditions (other predicates).
func HasStageWith(preds ...predicate.Stage) predicate.MCPInteraction {
	return predicate.MCPInteraction(func(s *sql.Selector) {
		step := newStageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentExecution applies the HasEdge predicate on the "agent_execution" edge.
func HasAgentExecution() predicate.MCPInteraction {
	return predicate.MCPInteraction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AgentExecutionTable, AgentExecutionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentExecutionWith applies the HasEdge predicate on the "agent_execution" edge with a given conditions (other predicates).
func HasAgentExecutionWith(preds ...predicate.AgentExecution) predicate.MCPInteraction {
	return predicate.MCPInteraction(func(s *sql.Selector) {
		step := newAgentExecutionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTimelineEvents applies the HasEdge predicate on the "timeline_events" edge.
func HasTimelineEvents() predicate.MCPInteraction {
	return predicate.MCPInteraction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TimelineEventsTable, TimelineEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTimelineEventsWith applies the HasEdge predicate on the "timeline_events" edge with a given conditions (other predicates).
func HasTimelineEventsWith(preds ...predicate.TimelineEvent) predicate.MCPInteraction {
	return predicate.MCPInteraction(func(s *sql.Selector) {
		step := newTimelineEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MCPInteraction) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MCPInteraction) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MCPInteraction) predicate.MCPInteraction {
	return predicate.MCPInteraction(sql.NotPredicates(p))
}
