// Code generated by ent, DO NOT EDIT.

package timelineevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContainsFold(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldSessionID, v))
}

// StageID applies equality check predicate on the "stage_id" field. It's identical to StageIDEQ.
func StageID(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldStageID, v))
}

// ExecutionID applies equality check predicate on the "execution_id" field. It's identical to ExecutionIDEQ.
func ExecutionID(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldExecutionID, v))
}

// SequenceNumber applies equality check predicate on the "sequence_number" field. It's identical to SequenceNumberEQ.
func SequenceNumber(v int) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldSequenceNumber, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldContent, v))
}

// LlmInteractionID applies equality check predicate on the "llm_interaction_id" field. It's identical to LlmInteractionIDEQ.
func LlmInteractionID(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldLlmInteractionID, v))
}

// McpInteractionID applies equality check predicate on the "mcp_interaction_id" field. It's identical to McpInteractionIDEQ.
func McpInteractionID(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldMcpInteractionID, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContainsFold(FieldSessionID, v))
}

// StageIDEQ applies the EQ predicate on the "stage_id" field.
func StageIDEQ(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldStageID, v))
}

// StageIDNEQ applies the NEQ predicate on the "stage_id" field.
func StageIDNEQ(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNEQ(FieldStageID, v))
}

// StageIDIn applies the In predicate on the "stage_id" field.
func StageIDIn(vs ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIn(FieldStageID, vs...))
}

// StageIDNotIn applies the NotIn predicate on the "stage_id" field.
func StageIDNotIn(vs ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotIn(FieldStageID, vs...))
}

// StageIDGT applies the GT predicate on the "stage_id" field.
func StageIDGT(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGT(FieldStageID, v))
}

// StageIDGTE applies the GTE predicate on the "stage_id" field.
func StageIDGTE(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGTE(FieldStageID, v))
}

// StageIDLT applies the LT predicate on the "stage_id" field.
func StageIDLT(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLT(FieldStageID, v))
}

// StageIDLTE applies the LTE predicate on the "stage_id" field.
func StageIDLTE(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLTE(FieldStageID, v))
}

// StageIDContains applies the Contains predicate on the "stage_id" field.
func StageIDContains(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContains(FieldStageID, v))
}

// StageIDHasPrefix applies the HasPrefix predicate on the "stage_id" field.
func StageIDHasPrefix(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldHasPrefix(FieldStageID, v))
}

// StageIDHasSuffix applies the HasSuffix predicate on the "stage_id" field.
func StageIDHasSuffix(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldHasSuffix(FieldStageID, v))
}

// StageIDIsNil applies the IsNil predicate on the "stage_id" field.
func StageIDIsNil() predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIsNull(FieldStageID))
}

// StageIDNotNil applies the NotNil predicate on the "stage_id" field.
func StageIDNotNil() predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotNull(FieldStageID))
}

// StageIDEqualFold applies the EqualFold predicate on the "stage_id" field.
func StageIDEqualFold(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEqualFold(FieldStageID, v))
}

// StageIDContainsFold applies the ContainsFold predicate on the "stage_id" field.
func StageIDContainsFold(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContainsFold(FieldStageID, v))
}

// ExecutionIDEQ applies the EQ predicate on the "execution_id" field.
func ExecutionIDEQ(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldExecutionID, v))
}

// ExecutionIDNEQ applies the NEQ predicate on the "execution_id" field.
func ExecutionIDNEQ(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNEQ(FieldExecutionID, v))
}

// ExecutionIDIn applies the In predicate on the "execution_id" field.
func ExecutionIDIn(vs ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIn(FieldExecutionID, vs...))
}

// ExecutionIDNotIn applies the NotIn predicate on the "execution_id" field.
func ExecutionIDNotIn(vs ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotIn(FieldExecutionID, vs...))
}

// ExecutionIDGT applies the GT predicate on the "execution_id" field.
func ExecutionIDGT(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGT(FieldExecutionID, v))
}

// ExecutionIDGTE applies the GTE predicate on the "execution_id" field.
func ExecutionIDGTE(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGTE(FieldExecutionID, v))
}

// ExecutionIDLT applies the LT predicate on the "execution_id" field.
func ExecutionIDLT(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLT(FieldExecutionID, v))
}

// ExecutionIDLTE applies the LTE predicate on the "execution_id" field.
func ExecutionIDLTE(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLTE(FieldExecutionID, v))
}

// ExecutionIDContains applies the Contains predicate on the "execution_id" field.
func ExecutionIDContains(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContains(FieldExecutionID, v))
}

// ExecutionIDHasPrefix applies the HasPrefix predicate on the "execution_id" field.
func ExecutionIDHasPrefix(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldHasPrefix(FieldExecutionID, v))
}

// ExecutionIDHasSuffix applies the HasSuffix predicate on the "execution_id" field.
func ExecutionIDHasSuffix(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldHasSuffix(FieldExecutionID, v))
}

// ExecutionIDIsNil applies the IsNil predicate on the "execution_id" field.
func ExecutionIDIsNil() predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIsNull(FieldExecutionID))
}

// ExecutionIDNotNil applies the NotNil predicate on the "execution_id" field.
func ExecutionIDNotNil() predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotNull(FieldExecutionID))
}

// ExecutionIDEqualFold applies the EqualFold predicate on the "execution_id" field.
func ExecutionIDEqualFold(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEqualFold(FieldExecutionID, v))
}

// ExecutionIDContainsFold applies the ContainsFold predicate on the "execution_id" field.
func ExecutionIDContainsFold(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContainsFold(FieldExecutionID, v))
}

// SequenceNumberEQ applies the EQ predicate on the "sequence_number" field.
func SequenceNumberEQ(v int) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldSequenceNumber, v))
}

// SequenceNumberNEQ applies the NEQ predicate on the "sequence_number" field.
func SequenceNumberNEQ(v int) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNEQ(FieldSequenceNumber, v))
}

// SequenceNumberIn applies the In predicate on the "sequence_number" field.
func SequenceNumberIn(vs ...int) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIn(FieldSequenceNumber, vs...))
}

// SequenceNumberNotIn applies the NotIn predicate on the "sequence_number" field.
func SequenceNumberNotIn(vs ...int) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotIn(FieldSequenceNumber, vs...))
}

// SequenceNumberGT applies the GT predicate on the "sequence_number" field.
func SequenceNumberGT(v int) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGT(FieldSequenceNumber, v))
}

// SequenceNumberGTE applies the GTE predicate on the "sequence_number" field.
func SequenceNumberGTE(v int) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGTE(FieldSequenceNumber, v))
}

// SequenceNumberLT applies the LT predicate on the "sequence_number" field.
func SequenceNumberLT(v int) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLT(FieldSequenceNumber, v))
}

// SequenceNumberLTE applies the LTE predicate on the "sequence_number" field.
func SequenceNumberLTE(v int) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLTE(FieldSequenceNumber, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v EventType) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v EventType) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...EventType) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...EventType) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContainsFold(FieldContent, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotNull(FieldMetadata))
}

// LlmInteractionIDEQ applies the EQ predicate on the "llm_interaction_id" field.
func LlmInteractionIDEQ(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldLlmInteractionID, v))
}

// LlmInteractionIDNEQ applies the NEQ predicate on the "llm_interaction_id" field.
func LlmInteractionIDNEQ(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNEQ(FieldLlmInteractionID, v))
}

// LlmInteractionIDIn applies the In predicate on the "llm_interaction_id" field.
func LlmInteractionIDIn(vs ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIn(FieldLlmInteractionID, vs...))
}

// LlmInteractionIDNotIn applies the NotIn predicate on the "llm_interaction_id" field.
func LlmInteractionIDNotIn(vs ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotIn(FieldLlmInteractionID, vs...))
}

// LlmInteractionIDGT applies the GT predicate on the "llm_interaction_id" field.
func LlmInteractionIDGT(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGT(FieldLlmInteractionID, v))
}

// LlmInteractionIDGTE applies the GTE predicate on the "llm_interaction_id" field.
func LlmInteractionIDGTE(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGTE(FieldLlmInteractionID, v))
}

// LlmInteractionIDLT applies the LT predicate on the "llm_interaction_id" field.
func LlmInteractionIDLT(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLT(FieldLlmInteractionID, v))
}

// LlmInteractionIDLTE applies the LTE predicate on the "llm_interaction_id" field.
func LlmInteractionIDLTE(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLTE(FieldLlmInteractionID, v))
}

// LlmInteractionIDContains applies the Contains predicate on the "llm_interaction_id" field.
func LlmInteractionIDContains(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContains(FieldLlmInteractionID, v))
}

// LlmInteractionIDHasPrefix applies the HasPrefix predicate on the "llm_interaction_id" field.
func LlmInteractionIDHasPrefix(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldHasPrefix(FieldLlmInteractionID, v))
}

// LlmInteractionIDHasSuffix applies the HasSuffix predicate on the "llm_interaction_id" field.
func LlmInteractionIDHasSuffix(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldHasSuffix(FieldLlmInteractionID, v))
}

// LlmInteractionIDIsNil applies the IsNil predicate on the "llm_interaction_id" field.
func LlmInteractionIDIsNil() predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIsNull(FieldLlmInteractionID))
}

// LlmInteractionIDNotNil applies the NotNil predicate on the "llm_interaction_id" field.
func LlmInteractionIDNotNil() predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotNull(FieldLlmInteractionID))
}

// LlmInteractionIDEqualFold applies the EqualFold predicate on the "llm_interaction_id" field.
func LlmInteractionIDEqualFold(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEqualFold(FieldLlmInteractionID, v))
}

// LlmInteractionIDContainsFold applies the ContainsFold predicate on the "llm_interaction_id" field.
func LlmInteractionIDContainsFold(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContainsFold(FieldLlmInteractionID, v))
}

// McpInteractionIDEQ applies the EQ predicate on the "mcp_interaction_id" field.
func McpInteractionIDEQ(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEQ(FieldMcpInteractionID, v))
}

// McpInteractionIDNEQ applies the NEQ predicate on the "mcp_interaction_id" field.
func McpInteractionIDNEQ(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNEQ(FieldMcpInteractionID, v))
}

// McpInteractionIDIn applies the In predicate on the "mcp_interaction_id" field.
func McpInteractionIDIn(vs ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIn(FieldMcpInteractionID, vs...))
}

// McpInteractionIDNotIn applies the NotIn predicate on the "mcp_interaction_id" field.
func McpInteractionIDNotIn(vs ...string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotIn(FieldMcpInteractionID, vs...))
}

// McpInteractionIDGT applies the GT predicate on the "mcp_interaction_id" field.
func McpInteractionIDGT(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGT(FieldMcpInteractionID, v))
}

// McpInteractionIDGTE applies the GTE predicate on the "mcp_interaction_id" field.
func McpInteractionIDGTE(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldGTE(FieldMcpInteractionID, v))
}

// McpInteractionIDLT applies the LT predicate on the "mcp_interaction_id" field.
func McpInteractionIDLT(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLT(FieldMcpInteractionID, v))
}

// McpInteractionIDLTE applies the LTE predicate on the "mcp_interaction_id" field.
func McpInteractionIDLTE(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldLTE(FieldMcpInteractionID, v))
}

// McpInteractionIDContains applies the Contains predicate on the "mcp_interaction_id" field.
func McpInteractionIDContains(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContains(FieldMcpInteractionID, v))
}

// McpInteractionIDHasPrefix applies the HasPrefix predicate on the "mcp_interaction_id" field.
func McpInteractionIDHasPrefix(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldHasPrefix(FieldMcpInteractionID, v))
}

// McpInteractionIDHasSuffix applies the HasSuffix predicate on the "mcp_interaction_id" field.
func McpInteractionIDHasSuffix(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldHasSuffix(FieldMcpInteractionID, v))
}

// McpInteractionIDIsNil applies the IsNil predicate on the "mcp_interaction_id" field.
func McpInteractionIDIsNil() predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldIsNull(FieldMcpInteractionID))
}

// McpInteractionIDNotNil applies the NotNil predicate on the "mcp_interaction_id" field.
func McpInteractionIDNotNil() predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldNotNull(FieldMcpInteractionID))
}

// McpInteractionIDEqualFold applies the EqualFold predicate on the "mcp_interaction_id" field.
func McpInteractionIDEqualFold(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldEqualFold(FieldMcpInteractionID, v))
}

// McpInteractionIDContainsFold applies the ContainsFold predicate on the "mcp_interaction_id" field.
func McpInteractionIDContainsFold(v string) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.FieldContainsFold(FieldMcpInteractionID, v))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.TimelineEvent {
	return predicate.TimelineEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.AlertSession) predicate.TimelineEvent {
	return predicate.TimelineEvent(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStage applies the HasEdge predicate on the "stage" edge.
func HasStage() predicate.TimelineEvent {
	return predicate.TimelineEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StageTable, StageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStageWith applies the HasEdge predicate on the "stage" edge with a given conditions (other predicates).
func HasStageWith(preds ...predicate.Stage) predicate.TimelineEvent {
	return predicate.TimelineEvent(func(s *sql.Selector) {
		step := newStageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAgentExecution applies the HasEdge predicate on the "agent_execution" edge.
func HasAgentExecution() predicate.TimelineEvent {
	return predicate.TimelineEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AgentExecutionTable, AgentExecutionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAgentExecutionWith applies the HasEdge predicate on the "agent_execution" edge with a given conditions (other predicates).
func HasAgentExecutionWith(preds ...predicate.AgentExecution) predicate.TimelineEvent {
	return predicate.TimelineEvent(func(s *sql.Selector) {
		step := newAgentExecutionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLlmInteraction applies the HasEdge predicate on the "llm_interaction" edge.
func HasLlmInteraction() predicate.TimelineEvent {
	return predicate.TimelineEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LlmInteractionTable, LlmInteractionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLlmInteractionWith applies the HasEdge predicate on the "llm_interaction" edge with a given conditions (other predicates).
func HasLlmInteractionWith(preds ...predicate.LLMInteraction) predicate.TimelineEvent {
	return predicate.TimelineEvent(func(s *sql.Selector) {
		step := newLlmInteractionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMcpInteraction applies the HasEdge predicate on the "mcp_interaction" edge.
func HasMcpInteraction() predicate.TimelineEvent {
	return predicate.TimelineEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, McpInteractionTable, McpInteractionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMcpInteractionWith applies the HasEdge predicate on the "mcp_interaction" edge with a given conditions (other predicates).
func HasMcpInteractionWith(preds ...predicate.MCPInteraction) predicate.TimelineEvent {
	return predicate.TimelineEvent(func(s *sql.Selector) {
		step := newMcpInteractionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TimelineEvent) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TimelineEvent) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TimelineEvent) predicate.TimelineEvent {
	return predicate.TimelineEvent(sql.NotPredicates(p))
}
