// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: llm_service.proto

package llmv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Role int32

const (
	Message_ROLE_UNSPECIFIED Message_Role = 0
	Message_ROLE_SYSTEM      Message_Role = 1
	Message_ROLE_USER        Message_Role = 2
	Message_ROLE_ASSISTANT   Message_Role = 3
)

// Enum value maps for Message_Role.
var (
	Message_Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_SYSTEM",
		2: "ROLE_USER",
		3: "ROLE_ASSISTANT",
	}
	Message_Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_SYSTEM":      1,
		"ROLE_USER":        2,
		"ROLE_ASSISTANT":   3,
	}
)

func (x Message_Role) Enum() *Message_Role {
	p := new(Message_Role)
	*p = x
	return p
}

func (x Message_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_llm_service_proto_enumTypes[0].Descriptor()
}

func (Message_Role) Type() protoreflect.EnumType {
	return &file_llm_service_proto_enumTypes[0]
}

func (x Message_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Role.Descriptor instead.
func (Message_Role) EnumDescriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{1, 0}
}

// ThinkingRequest contains the conversation and configuration
type ThinkingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Temperature   *float32               `protobuf:"fixed32,4,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	MaxTokens     *int32                 `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingRequest) Reset() {
	*x = ThinkingRequest{}
	mi := &file_llm_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingRequest) ProtoMessage() {}

func (x *ThinkingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingRequest.ProtoReflect.Descriptor instead.
func (*ThinkingRequest) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{0}
}

func (x *ThinkingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ThinkingRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ThinkingRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ThinkingRequest) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *ThinkingRequest) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

// Message represents a single conversation message
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          Message_Role           `protobuf:"varint,1,opt,name=role,proto3,enum=llm.v1.Message_Role" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_llm_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() Message_Role {
	if x != nil {
		return x.Role
	}
	return Message_ROLE_UNSPECIFIED
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ThinkingChunk is a streaming response chunk
type ThinkingChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ChunkType:
	//
	//	*ThinkingChunk_Thinking
	//	*ThinkingChunk_Response
	//	*ThinkingChunk_Error
	ChunkType     isThinkingChunk_ChunkType `protobuf_oneof:"chunk_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingChunk) Reset() {
	*x = ThinkingChunk{}
	mi := &file_llm_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingChunk) ProtoMessage() {}

func (x *ThinkingChunk) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingChunk.ProtoReflect.Descriptor instead.
func (*ThinkingChunk) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{2}
}

func (x *ThinkingChunk) GetChunkType() isThinkingChunk_ChunkType {
	if x != nil {
		return x.ChunkType
	}
	return nil
}

func (x *ThinkingChunk) GetThinking() *ThinkingContent {
	if x != nil {
		if x, ok := x.ChunkType.(*ThinkingChunk_Thinking); ok {
			return x.Thinking
		}
	}
	return nil
}

func (x *ThinkingChunk) GetResponse() *ResponseContent {
	if x != nil {
		if x, ok := x.ChunkType.(*ThinkingChunk_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *ThinkingChunk) GetError() *ErrorContent {
	if x != nil {
		if x, ok := x.ChunkType.(*ThinkingChunk_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isThinkingChunk_ChunkType interface {
	isThinkingChunk_ChunkType()
}

type ThinkingChunk_Thinking struct {
	Thinking *ThinkingContent `protobuf:"bytes,1,opt,name=thinking,proto3,oneof"`
}

type ThinkingChunk_Response struct {
	Response *ResponseContent `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type ThinkingChunk_Error struct {
	Error *ErrorContent `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ThinkingChunk_Thinking) isThinkingChunk_ChunkType() {}

func (*ThinkingChunk_Response) isThinkingChunk_ChunkType() {}

func (*ThinkingChunk_Error) isThinkingChunk_ChunkType() {}

// ThinkingContent contains thinking/reasoning text
type ThinkingContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsComplete    bool                   `protobuf:"varint,2,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingContent) Reset() {
	*x = ThinkingContent{}
	mi := &file_llm_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingContent) ProtoMessage() {}

func (x *ThinkingContent) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingContent.ProtoReflect.Descriptor instead.
func (*ThinkingContent) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{3}
}

func (x *ThinkingContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ThinkingContent) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

// ResponseContent contains the actual response text
type ResponseContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsComplete    bool                   `protobuf:"varint,2,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"` // No more tool calls expected
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseContent) Reset() {
	*x = ResponseContent{}
	mi := &file_llm_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseContent) ProtoMessage() {}

func (x *ResponseContent) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseContent.ProtoReflect.Descriptor instead.
func (*ResponseContent) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ResponseContent) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *ResponseContent) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

// ErrorContent contains error information
type ErrorContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,2,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorContent) Reset() {
	*x = ErrorContent{}
	mi := &file_llm_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorContent) ProtoMessage() {}

func (x *ErrorContent) ProtoReflect() protoreflect.Message {
	mi := &file_llm_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorContent.ProtoReflect.Descriptor instead.
func (*ErrorContent) Descriptor() ([]byte, []int) {
	return file_llm_service_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorContent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorContent) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

var File_llm_service_proto protoreflect.FileDescriptor

const file_llm_service_proto_rawDesc = "" +
	"\n" +
	"\x11llm_service.proto\x12\x06llm.v1\"\xdd\x01\n" +
	"\x0fThinkingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12+\n" +
	"\bmessages\x18\x02 \x03(\v2\x0f.llm.v1.MessageR\bmessages\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12%\n" +
	"\vtemperature\x18\x04 \x01(\x02H\x00R\vtemperature\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05H\x01R\tmaxTokens\x88\x01\x01B\x0e\n" +
	"\f_temperatureB\r\n" +
	"\v_max_tokens\"\x9f\x01\n" +
	"\aMessage\x12(\n" +
	"\x04role\x18\x01 \x01(\x0e2\x14.llm.v1.Message.RoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"P\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROLE_SYSTEM\x10\x01\x12\r\n" +
	"\tROLE_USER\x10\x02\x12\x12\n" +
	"\x0eROLE_ASSISTANT\x10\x03\"\xb9\x01\n" +
	"\rThinkingChunk\x125\n" +
	"\bthinking\x18\x01 \x01(\v2\x17.llm.v1.ThinkingContentH\x00R\bthinking\x125\n" +
	"\bresponse\x18\x02 \x01(\v2\x17.llm.v1.ResponseContentH\x00R\bresponse\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x14.llm.v1.ErrorContentH\x00R\x05errorB\f\n" +
	"\n" +
	"chunk_type\"L\n" +
	"\x0fThinkingContent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vis_complete\x18\x02 \x01(\bR\n" +
	"isComplete\"g\n" +
	"\x0fResponseContent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vis_complete\x18\x02 \x01(\bR\n" +
	"isComplete\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\"F\n" +
	"\fErrorContent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x02 \x01(\bR\tretryable2V\n" +
	"\n" +
	"LLMService\x12H\n" +
	"\x14GenerateWithThinking\x12\x17.llm.v1.ThinkingRequest\x1a\x15.llm.v1.ThinkingChunk0\x01B&Z$github.com/tarsy/pkg/pb/llm/v1;llmv1b\x06proto3"

var (
	file_llm_service_proto_rawDescOnce sync.Once
	file_llm_service_proto_rawDescData []byte
)

func file_llm_service_proto_rawDescGZIP() []byte {
	file_llm_service_proto_rawDescOnce.Do(func() {
		file_llm_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_service_proto_rawDesc), len(file_llm_service_proto_rawDesc)))
	})
	return file_llm_service_proto_rawDescData
}

var file_llm_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_llm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_llm_service_proto_goTypes = []any{
	(Message_Role)(0),       // 0: llm.v1.Message.Role
	(*ThinkingRequest)(nil), // 1: llm.v1.ThinkingRequest
	(*Message)(nil),         // 2: llm.v1.Message
	(*ThinkingChunk)(nil),   // 3: llm.v1.ThinkingChunk
	(*ThinkingContent)(nil), // 4: llm.v1.ThinkingContent
	(*ResponseContent)(nil), // 5: llm.v1.ResponseContent
	(*ErrorContent)(nil),    // 6: llm.v1.ErrorContent
}
var file_llm_service_proto_depIdxs = []int32{
	2, // 0: llm.v1.ThinkingRequest.messages:type_name -> llm.v1.Message
	0, // 1: llm.v1.Message.role:type_name -> llm.v1.Message.Role
	4, // 2: llm.v1.ThinkingChunk.thinking:type_name -> llm.v1.ThinkingContent
	5, // 3: llm.v1.ThinkingChunk.response:type_name -> llm.v1.ResponseContent
	6, // 4: llm.v1.ThinkingChunk.error:type_name -> llm.v1.ErrorContent
	1, // 5: llm.v1.LLMService.GenerateWithThinking:input_type -> llm.v1.ThinkingRequest
	3, // 6: llm.v1.LLMService.GenerateWithThinking:output_type -> llm.v1.ThinkingChunk
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_llm_service_proto_init() }
func file_llm_service_proto_init() {
	if File_llm_service_proto != nil {
		return
	}
	file_llm_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_llm_service_proto_msgTypes[2].OneofWrappers = []any{
		(*ThinkingChunk_Thinking)(nil),
		(*ThinkingChunk_Response)(nil),
		(*ThinkingChunk_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_service_proto_rawDesc), len(file_llm_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_service_proto_goTypes,
		DependencyIndexes: file_llm_service_proto_depIdxs,
		EnumInfos:         file_llm_service_proto_enumTypes,
		MessageInfos:      file_llm_service_proto_msgTypes,
	}.Build()
	File_llm_service_proto = out.File
	file_llm_service_proto_goTypes = nil
	file_llm_service_proto_depIdxs = nil
}
