// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/codeready-toolchain/tarsy/ent/agentexecution"
	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/stage"
)

// AgentExecution is the model entity for the AgentExecution schema.
type AgentExecution struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// StageID holds the value of the "stage_id" field.
	StageID string `json:"stage_id,omitempty"`
	// Denormalized for performance
	SessionID string `json:"session_id,omitempty"`
	// e.g., 'KubernetesAgent', 'ArgoCDAgent'
	AgentName string `json:"agent_name,omitempty"`
	// 1 for single, 1-N for parallel
	AgentIndex int `json:"agent_index,omitempty"`
	// Status holds the value of the "status" field.
	Status agentexecution.Status `json:"status,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs *int `json:"duration_ms,omitempty"`
	// Error details if failed
	ErrorMessage *string `json:"error_message,omitempty"`
	// LLM backend used: 'google-native' or 'langchain' (for observability)
	LlmBackend string `json:"llm_backend,omitempty"`
	// Resolved LLM provider name (for observability, e.g. 'gemini-2.5-pro')
	LlmProvider *string `json:"llm_provider,omitempty"`
	// For orchestrator sub-agents: links to the parent orchestrator execution
	ParentExecutionID *string `json:"parent_execution_id,omitempty"`
	// Task description from orchestrator dispatch
	Task *string `json:"task,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentExecutionQuery when eager-loading is set.
	Edges        AgentExecutionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentExecutionEdges holds the relations/edges for other nodes in the graph.
type AgentExecutionEdges struct {
	// Stage holds the value of the stage edge.
	Stage *Stage `json:"stage,omitempty"`
	// Session holds the value of the session edge.
	Session *AlertSession `json:"session,omitempty"`
	// TimelineEvents holds the value of the timeline_events edge.
	TimelineEvents []*TimelineEvent `json:"timeline_events,omitempty"`
	// Messages holds the value of the messages edge.
	Messages []*Message `json:"messages,omitempty"`
	// LlmInteractions holds the value of the llm_interactions edge.
	LlmInteractions []*LLMInteraction `json:"llm_interactions,omitempty"`
	// McpInteractions holds the value of the mcp_interactions edge.
	McpInteractions []*MCPInteraction `json:"mcp_interactions,omitempty"`
	// SubAgents holds the value of the sub_agents edge.
	SubAgents []*AgentExecution `json:"sub_agents,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *AgentExecution `json:"parent,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// StageOrErr returns the Stage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentExecutionEdges) StageOrErr() (*Stage, error) {
	if e.Stage != nil {
		return e.Stage, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: stage.Label}
	}
	return nil, &NotLoadedError{edge: "stage"}
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentExecutionEdges) SessionOrErr() (*AlertSession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: alertsession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// TimelineEventsOrErr returns the TimelineEvents value or an error if the edge
// was not loaded in eager-loading.
func (e AgentExecutionEdges) TimelineEventsOrErr() ([]*TimelineEvent, error) {
	if e.loadedTypes[2] {
		return e.TimelineEvents, nil
	}
	return nil, &NotLoadedError{edge: "timeline_events"}
}

// MessagesOrErr returns the Messages value or an error if the edge
// was not loaded in eager-loading.
func (e AgentExecutionEdges) MessagesOrErr() ([]*Message, error) {
	if e.loadedTypes[3] {
		return e.Messages, nil
	}
	return nil, &NotLoadedError{edge: "messages"}
}

// LlmInteractionsOrErr returns the LlmInteractions value or an error if the edge
// was not loaded in eager-loading.
func (e AgentExecutionEdges) LlmInteractionsOrErr() ([]*LLMInteraction, error) {
	if e.loadedTypes[4] {
		return e.LlmInteractions, nil
	}
	return nil, &NotLoadedError{edge: "llm_interactions"}
}

// McpInteractionsOrErr returns the McpInteractions value or an error if the edge
// was not loaded in eager-loading.
func (e AgentExecutionEdges) McpInteractionsOrErr() ([]*MCPInteraction, error) {
	if e.loadedTypes[5] {
		return e.McpInteractions, nil
	}
	return nil, &NotLoadedError{edge: "mcp_interactions"}
}

// SubAgentsOrErr returns the SubAgents value or an error if the edge
// was not loaded in eager-loading.
func (e AgentExecutionEdges) SubAgentsOrErr() ([]*AgentExecution, error) {
	if e.loadedTypes[6] {
		return e.SubAgents, nil
	}
	return nil, &NotLoadedError{edge: "sub_agents"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentExecutionEdges) ParentOrErr() (*AgentExecution, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[7] {
		return nil, &NotFoundError{label: agentexecution.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentExecution) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentexecution.FieldAgentIndex, agentexecution.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case agentexecution.FieldID, agentexecution.FieldStageID, agentexecution.FieldSessionID, agentexecution.FieldAgentName, agentexecution.FieldStatus, agentexecution.FieldErrorMessage, agentexecution.FieldLlmBackend, agentexecution.FieldLlmProvider, agentexecution.FieldParentExecutionID, agentexecution.FieldTask:
			values[i] = new(sql.NullString)
		case agentexecution.FieldStartedAt, agentexecution.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentExecution fields.
func (_m *AgentExecution) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentexecution.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case agentexecution.FieldStageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stage_id", values[i])
			} else if value.Valid {
				_m.StageID = value.String
			}
		case agentexecution.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case agentexecution.FieldAgentName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_name", values[i])
			} else if value.Valid {
				_m.AgentName = value.String
			}
		case agentexecution.FieldAgentIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field agent_index", values[i])
			} else if value.Valid {
				_m.AgentIndex = int(value.Int64)
			}
		case agentexecution.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = agentexecution.Status(value.String)
			}
		case agentexecution.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case agentexecution.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case agentexecution.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = new(int)
				*_m.DurationMs = int(value.Int64)
			}
		case agentexecution.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case agentexecution.FieldLlmBackend:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field llm_backend", values[i])
			} else if value.Valid {
				_m.LlmBackend = value.String
			}
		case agentexecution.FieldLlmProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field llm_provider", values[i])
			} else if value.Valid {
				_m.LlmProvider = new(string)
				*_m.LlmProvider = value.String
			}
		case agentexecution.FieldParentExecutionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_execution_id", values[i])
			} else if value.Valid {
				_m.ParentExecutionID = new(string)
				*_m.ParentExecutionID = value.String
			}
		case agentexecution.FieldTask:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task", values[i])
			} else if value.Valid {
				_m.Task = new(string)
				*_m.Task = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentExecution.
// This includes values selected through modifiers, order, etc.
func (_m *AgentExecution) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryStage queries the "stage" edge of the AgentExecution entity.
func (_m *AgentExecution) QueryStage() *StageQuery {
	return NewAgentExecutionClient(_m.config).QueryStage(_m)
}

// QuerySession queries the "session" edge of the AgentExecution entity.
func (_m *AgentExecution) QuerySession() *AlertSessionQuery {
	return NewAgentExecutionClient(_m.config).QuerySession(_m)
}

// QueryTimelineEvents queries the "timeline_events" edge of the AgentExecution entity.
func (_m *AgentExecution) QueryTimelineEvents() *TimelineEventQuery {
	return NewAgentExecutionClient(_m.config).QueryTimelineEvents(_m)
}

// QueryMessages queries the "messages" edge of the AgentExecution entity.
func (_m *AgentExecution) QueryMessages() *MessageQuery {
	return NewAgentExecutionClient(_m.config).QueryMessages(_m)
}

// QueryLlmInteractions queries the "llm_interactions" edge of the AgentExecution entity.
func (_m *AgentExecution) QueryLlmInteractions() *LLMInteractionQuery {
	return NewAgentExecutionClient(_m.config).QueryLlmInteractions(_m)
}

// QueryMcpInteractions queries the "mcp_interactions" edge of the AgentExecution entity.
func (_m *AgentExecution) QueryMcpInteractions() *MCPInteractionQuery {
	return NewAgentExecutionClient(_m.config).QueryMcpInteractions(_m)
}

// QuerySubAgents queries the "sub_agents" edge of the AgentExecution entity.
func (_m *AgentExecution) QuerySubAgents() *AgentExecutionQuery {
	return NewAgentExecutionClient(_m.config).QuerySubAgents(_m)
}

// QueryParent queries the "parent" edge of the AgentExecution entity.
func (_m *AgentExecution) QueryParent() *AgentExecutionQuery {
	return NewAgentExecutionClient(_m.config).QueryParent(_m)
}

// Update returns a builder for updating this AgentExecution.
// Note that you need to call AgentExecution.Unwrap() before calling this method if this AgentExecution
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentExecution) Update() *AgentExecutionUpdateOne {
	return NewAgentExecutionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentExecution entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentExecution) Unwrap() *AgentExecution {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentExecution is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentExecution) String() string {
	var builder strings.Builder
	builder.WriteString("AgentExecution(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("stage_id=")
	builder.WriteString(_m.StageID)
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("agent_name=")
	builder.WriteString(_m.AgentName)
	builder.WriteString(", ")
	builder.WriteString("agent_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.AgentIndex))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DurationMs; v != nil {
		builder.WriteString("duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("llm_backend=")
	builder.WriteString(_m.LlmBackend)
	builder.WriteString(", ")
	if v := _m.LlmProvider; v != nil {
		builder.WriteString("llm_provider=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ParentExecutionID; v != nil {
		builder.WriteString("parent_execution_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Task; v != nil {
		builder.WriteString("task=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// AgentExecutions is a parsable slice of AgentExecution.
type AgentExecutions []*AgentExecution
