// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/agentexecution"
	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/llminteraction"
	"github.com/codeready-toolchain/tarsy/ent/mcpinteraction"
	"github.com/codeready-toolchain/tarsy/ent/message"
	"github.com/codeready-toolchain/tarsy/ent/stage"
	"github.com/codeready-toolchain/tarsy/ent/timelineevent"
)

// AgentExecutionCreate is the builder for creating a AgentExecution entity.
type AgentExecutionCreate struct {
	config
	mutation *AgentExecutionMutation
	hooks    []Hook
}

// SetStageID sets the "stage_id" field.
func (_c *AgentExecutionCreate) SetStageID(v string) *AgentExecutionCreate {
	_c.mutation.SetStageID(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *AgentExecutionCreate) SetSessionID(v string) *AgentExecutionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetAgentName sets the "agent_name" field.
func (_c *AgentExecutionCreate) SetAgentName(v string) *AgentExecutionCreate {
	_c.mutation.SetAgentName(v)
	return _c
}

// SetAgentIndex sets the "agent_index" field.
func (_c *AgentExecutionCreate) SetAgentIndex(v int) *AgentExecutionCreate {
	_c.mutation.SetAgentIndex(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *AgentExecutionCreate) SetStatus(v agentexecution.Status) *AgentExecutionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AgentExecutionCreate) SetNillableStatus(v *agentexecution.Status) *AgentExecutionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *AgentExecutionCreate) SetStartedAt(v time.Time) *AgentExecutionCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *AgentExecutionCreate) SetNillableStartedAt(v *time.Time) *AgentExecutionCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *AgentExecutionCreate) SetCompletedAt(v time.Time) *AgentExecutionCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *AgentExecutionCreate) SetNillableCompletedAt(v *time.Time) *AgentExecutionCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *AgentExecutionCreate) SetDurationMs(v int) *AgentExecutionCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *AgentExecutionCreate) SetNillableDurationMs(v *int) *AgentExecutionCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *AgentExecutionCreate) SetErrorMessage(v string) *AgentExecutionCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *AgentExecutionCreate) SetNillableErrorMessage(v *string) *AgentExecutionCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetIterationStrategy sets the "iteration_strategy" field.
func (_c *AgentExecutionCreate) SetIterationStrategy(v string) *AgentExecutionCreate {
	_c.mutation.SetIterationStrategy(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AgentExecutionCreate) SetID(v string) *AgentExecutionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetStage sets the "stage" edge to the Stage entity.
func (_c *AgentExecutionCreate) SetStage(v *Stage) *AgentExecutionCreate {
	return _c.SetStageID(v.ID)
}

// SetSession sets the "session" edge to the AlertSession entity.
func (_c *AgentExecutionCreate) SetSession(v *AlertSession) *AgentExecutionCreate {
	return _c.SetSessionID(v.ID)
}

// AddTimelineEventIDs adds the "timeline_events" edge to the TimelineEvent entity by IDs.
func (_c *AgentExecutionCreate) AddTimelineEventIDs(ids ...string) *AgentExecutionCreate {
	_c.mutation.AddTimelineEventIDs(ids...)
	return _c
}

// AddTimelineEvents adds the "timeline_events" edges to the TimelineEvent entity.
func (_c *AgentExecutionCreate) AddTimelineEvents(v ...*TimelineEvent) *AgentExecutionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTimelineEventIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_c *AgentExecutionCreate) AddMessageIDs(ids ...string) *AgentExecutionCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the Message entity.
func (_c *AgentExecutionCreate) AddMessages(v ...*Message) *AgentExecutionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// AddLlmInteractionIDs adds the "llm_interactions" edge to the LLMInteraction entity by IDs.
func (_c *AgentExecutionCreate) AddLlmInteractionIDs(ids ...string) *AgentExecutionCreate {
	_c.mutation.AddLlmInteractionIDs(ids...)
	return _c
}

// AddLlmInteractions adds the "llm_interactions" edges to the LLMInteraction entity.
func (_c *AgentExecutionCreate) AddLlmInteractions(v ...*LLMInteraction) *AgentExecutionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLlmInteractionIDs(ids...)
}

// AddMcpInteractionIDs adds the "mcp_interactions" edge to the MCPInteraction entity by IDs.
func (_c *AgentExecutionCreate) AddMcpInteractionIDs(ids ...string) *AgentExecutionCreate {
	_c.mutation.AddMcpInteractionIDs(ids...)
	return _c
}

// AddMcpInteractions adds the "mcp_interactions" edges to the MCPInteraction entity.
func (_c *AgentExecutionCreate) AddMcpInteractions(v ...*MCPInteraction) *AgentExecutionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMcpInteractionIDs(ids...)
}

// Mutation returns the AgentExecutionMutation object of the builder.
func (_c *AgentExecutionCreate) Mutation() *AgentExecutionMutation {
	return _c.mutation
}

// Save creates the AgentExecution in the database.
func (_c *AgentExecutionCreate) Save(ctx context.Context) (*AgentExecution, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentExecutionCreate) SaveX(ctx context.Context) *AgentExecution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentExecutionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentExecutionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentExecutionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := agentexecution.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentExecutionCreate) check() error {
	if _, ok := _c.mutation.StageID(); !ok {
		return &ValidationError{Name: "stage_id", err: errors.New(`ent: missing required field "AgentExecution.stage_id"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "AgentExecution.session_id"`)}
	}
	if _, ok := _c.mutation.AgentName(); !ok {
		return &ValidationError{Name: "agent_name", err: errors.New(`ent: missing required field "AgentExecution.agent_name"`)}
	}
	if _, ok := _c.mutation.AgentIndex(); !ok {
		return &ValidationError{Name: "agent_index", err: errors.New(`ent: missing required field "AgentExecution.agent_index"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AgentExecution.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := agentexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentExecution.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IterationStrategy(); !ok {
		return &ValidationError{Name: "iteration_strategy", err: errors.New(`ent: missing required field "AgentExecution.iteration_strategy"`)}
	}
	if len(_c.mutation.StageIDs()) == 0 {
		return &ValidationError{Name: "stage", err: errors.New(`ent: missing required edge "AgentExecution.stage"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "AgentExecution.session"`)}
	}
	return nil
}

func (_c *AgentExecutionCreate) sqlSave(ctx context.Context) (*AgentExecution, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AgentExecution.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentExecutionCreate) createSpec() (*AgentExecution, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentExecution{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentexecution.Table, sqlgraph.NewFieldSpec(agentexecution.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AgentName(); ok {
		_spec.SetField(agentexecution.FieldAgentName, field.TypeString, value)
		_node.AgentName = value
	}
	if value, ok := _c.mutation.AgentIndex(); ok {
		_spec.SetField(agentexecution.FieldAgentIndex, field.TypeInt, value)
		_node.AgentIndex = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(agentexecution.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(agentexecution.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(agentexecution.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(agentexecution.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(agentexecution.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.IterationStrategy(); ok {
		_spec.SetField(agentexecution.FieldIterationStrategy, field.TypeString, value)
		_node.IterationStrategy = value
	}
	if nodes := _c.mutation.StageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentexecution.StageTable,
			Columns: []string{agentexecution.StageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentexecution.SessionTable,
			Columns: []string{agentexecution.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertsession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TimelineEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentexecution.TimelineEventsTable,
			Columns: []string{agentexecution.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentexecution.MessagesTable,
			Columns: []string{agentexecution.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LlmInteractionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentexecution.LlmInteractionsTable,
			Columns: []string{agentexecution.LlmInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.McpInteractionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agentexecution.McpInteractionsTable,
			Columns: []string{agentexecution.McpInteractionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentExecutionCreateBulk is the builder for creating many AgentExecution entities in bulk.
type AgentExecutionCreateBulk struct {
	config
	err      error
	builders []*AgentExecutionCreate
}

// Save creates the AgentExecution entities in the database.
func (_c *AgentExecutionCreateBulk) Save(ctx context.Context) ([]*AgentExecution, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentExecution, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentExecutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentExecutionCreateBulk) SaveX(ctx context.Context) []*AgentExecution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentExecutionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentExecutionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
