// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/codeready-toolchain/tarsy/ent/chat"
	"github.com/codeready-toolchain/tarsy/ent/chatusermessage"
	"github.com/codeready-toolchain/tarsy/ent/stage"
)

// ChatUserMessage is the model entity for the ChatUserMessage schema.
type ChatUserMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ChatID holds the value of the "chat_id" field.
	ChatID string `json:"chat_id,omitempty"`
	// Question text
	Content string `json:"content,omitempty"`
	// User email
	Author string `json:"author,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatUserMessageQuery when eager-loading is set.
	Edges        ChatUserMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChatUserMessageEdges holds the relations/edges for other nodes in the graph.
type ChatUserMessageEdges struct {
	// Chat holds the value of the chat edge.
	Chat *Chat `json:"chat,omitempty"`
	// Response stage
	Stage *Stage `json:"stage,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChatOrErr returns the Chat value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatUserMessageEdges) ChatOrErr() (*Chat, error) {
	if e.Chat != nil {
		return e.Chat, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: chat.Label}
	}
	return nil, &NotLoadedError{edge: "chat"}
}

// StageOrErr returns the Stage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatUserMessageEdges) StageOrErr() (*Stage, error) {
	if e.Stage != nil {
		return e.Stage, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: stage.Label}
	}
	return nil, &NotLoadedError{edge: "stage"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatUserMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatusermessage.FieldID, chatusermessage.FieldChatID, chatusermessage.FieldContent, chatusermessage.FieldAuthor:
			values[i] = new(sql.NullString)
		case chatusermessage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatUserMessage fields.
func (_m *ChatUserMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatusermessage.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case chatusermessage.FieldChatID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chat_id", values[i])
			} else if value.Valid {
				_m.ChatID = value.String
			}
		case chatusermessage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case chatusermessage.FieldAuthor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author", values[i])
			} else if value.Valid {
				_m.Author = value.String
			}
		case chatusermessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatUserMessage.
// This includes values selected through modifiers, order, etc.
func (_m *ChatUserMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChat queries the "chat" edge of the ChatUserMessage entity.
func (_m *ChatUserMessage) QueryChat() *ChatQuery {
	return NewChatUserMessageClient(_m.config).QueryChat(_m)
}

// QueryStage queries the "stage" edge of the ChatUserMessage entity.
func (_m *ChatUserMessage) QueryStage() *StageQuery {
	return NewChatUserMessageClient(_m.config).QueryStage(_m)
}

// Update returns a builder for updating this ChatUserMessage.
// Note that you need to call ChatUserMessage.Unwrap() before calling this method if this ChatUserMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatUserMessage) Update() *ChatUserMessageUpdateOne {
	return NewChatUserMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatUserMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatUserMessage) Unwrap() *ChatUserMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatUserMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatUserMessage) String() string {
	var builder strings.Builder
	builder.WriteString("ChatUserMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("chat_id=")
	builder.WriteString(_m.ChatID)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("author=")
	builder.WriteString(_m.Author)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChatUserMessages is a parsable slice of ChatUserMessage.
type ChatUserMessages []*ChatUserMessage
