// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/chat"
	"github.com/codeready-toolchain/tarsy/ent/chatusermessage"
	"github.com/codeready-toolchain/tarsy/ent/stage"
)

// ChatCreate is the builder for creating a Chat entity.
type ChatCreate struct {
	config
	mutation *ChatMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *ChatCreate) SetSessionID(v string) *ChatCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatCreate) SetCreatedAt(v time.Time) *ChatCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatCreate) SetNillableCreatedAt(v *time.Time) *ChatCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ChatCreate) SetCreatedBy(v string) *ChatCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *ChatCreate) SetNillableCreatedBy(v *string) *ChatCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetChainID sets the "chain_id" field.
func (_c *ChatCreate) SetChainID(v string) *ChatCreate {
	_c.mutation.SetChainID(v)
	return _c
}

// SetPodID sets the "pod_id" field.
func (_c *ChatCreate) SetPodID(v string) *ChatCreate {
	_c.mutation.SetPodID(v)
	return _c
}

// SetNillablePodID sets the "pod_id" field if the given value is not nil.
func (_c *ChatCreate) SetNillablePodID(v *string) *ChatCreate {
	if v != nil {
		_c.SetPodID(*v)
	}
	return _c
}

// SetLastInteractionAt sets the "last_interaction_at" field.
func (_c *ChatCreate) SetLastInteractionAt(v time.Time) *ChatCreate {
	_c.mutation.SetLastInteractionAt(v)
	return _c
}

// SetNillableLastInteractionAt sets the "last_interaction_at" field if the given value is not nil.
func (_c *ChatCreate) SetNillableLastInteractionAt(v *time.Time) *ChatCreate {
	if v != nil {
		_c.SetLastInteractionAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChatCreate) SetID(v string) *ChatCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSession sets the "session" edge to the AlertSession entity.
func (_c *ChatCreate) SetSession(v *AlertSession) *ChatCreate {
	return _c.SetSessionID(v.ID)
}

// AddUserMessageIDs adds the "user_messages" edge to the ChatUserMessage entity by IDs.
func (_c *ChatCreate) AddUserMessageIDs(ids ...string) *ChatCreate {
	_c.mutation.AddUserMessageIDs(ids...)
	return _c
}

// AddUserMessages adds the "user_messages" edges to the ChatUserMessage entity.
func (_c *ChatCreate) AddUserMessages(v ...*ChatUserMessage) *ChatCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserMessageIDs(ids...)
}

// AddStageIDs adds the "stages" edge to the Stage entity by IDs.
func (_c *ChatCreate) AddStageIDs(ids ...string) *ChatCreate {
	_c.mutation.AddStageIDs(ids...)
	return _c
}

// AddStages adds the "stages" edges to the Stage entity.
func (_c *ChatCreate) AddStages(v ...*Stage) *ChatCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStageIDs(ids...)
}

// Mutation returns the ChatMutation object of the builder.
func (_c *ChatCreate) Mutation() *ChatMutation {
	return _c.mutation
}

// Save creates the Chat in the database.
func (_c *ChatCreate) Save(ctx context.Context) (*Chat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatCreate) SaveX(ctx context.Context) *Chat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chat.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "Chat.session_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Chat.created_at"`)}
	}
	if _, ok := _c.mutation.ChainID(); !ok {
		return &ValidationError{Name: "chain_id", err: errors.New(`ent: missing required field "Chat.chain_id"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "Chat.session"`)}
	}
	return nil
}

func (_c *ChatCreate) sqlSave(ctx context.Context) (*Chat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Chat.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatCreate) createSpec() (*Chat, *sqlgraph.CreateSpec) {
	var (
		_node = &Chat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chat.Table, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chat.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(chat.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.ChainID(); ok {
		_spec.SetField(chat.FieldChainID, field.TypeString, value)
		_node.ChainID = value
	}
	if value, ok := _c.mutation.PodID(); ok {
		_spec.SetField(chat.FieldPodID, field.TypeString, value)
		_node.PodID = &value
	}
	if value, ok := _c.mutation.LastInteractionAt(); ok {
		_spec.SetField(chat.FieldLastInteractionAt, field.TypeTime, value)
		_node.LastInteractionAt = &value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   chat.SessionTable,
			Columns: []string{chat.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertsession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.UserMessagesTable,
			Columns: []string{chat.UserMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatusermessage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.StagesTable,
			Columns: []string{chat.StagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatCreateBulk is the builder for creating many Chat entities in bulk.
type ChatCreateBulk struct {
	config
	err      error
	builders []*ChatCreate
}

// Save creates the Chat entities in the database.
func (_c *ChatCreateBulk) Save(ctx context.Context) ([]*Chat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Chat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatCreateBulk) SaveX(ctx context.Context) []*Chat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
