// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/chatusermessage"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
	"github.com/codeready-toolchain/tarsy/ent/stage"
)

// ChatUserMessageUpdate is the builder for updating ChatUserMessage entities.
type ChatUserMessageUpdate struct {
	config
	hooks     []Hook
	mutation  *ChatUserMessageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ChatUserMessageUpdate builder.
func (_u *ChatUserMessageUpdate) Where(ps ...predicate.ChatUserMessage) *ChatUserMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContent sets the "content" field.
func (_u *ChatUserMessageUpdate) SetContent(v string) *ChatUserMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChatUserMessageUpdate) SetNillableContent(v *string) *ChatUserMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *ChatUserMessageUpdate) SetAuthor(v string) *ChatUserMessageUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *ChatUserMessageUpdate) SetNillableAuthor(v *string) *ChatUserMessageUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetStageID sets the "stage" edge to the Stage entity by ID.
func (_u *ChatUserMessageUpdate) SetStageID(id string) *ChatUserMessageUpdate {
	_u.mutation.SetStageID(id)
	return _u
}

// SetNillableStageID sets the "stage" edge to the Stage entity by ID if the given value is not nil.
func (_u *ChatUserMessageUpdate) SetNillableStageID(id *string) *ChatUserMessageUpdate {
	if id != nil {
		_u = _u.SetStageID(*id)
	}
	return _u
}

// SetStage sets the "stage" edge to the Stage entity.
func (_u *ChatUserMessageUpdate) SetStage(v *Stage) *ChatUserMessageUpdate {
	return _u.SetStageID(v.ID)
}

// Mutation returns the ChatUserMessageMutation object of the builder.
func (_u *ChatUserMessageUpdate) Mutation() *ChatUserMessageMutation {
	return _u.mutation
}

// ClearStage clears the "stage" edge to the Stage entity.
func (_u *ChatUserMessageUpdate) ClearStage() *ChatUserMessageUpdate {
	_u.mutation.ClearStage()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatUserMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatUserMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatUserMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatUserMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatUserMessageUpdate) check() error {
	if _u.mutation.ChatCleared() && len(_u.mutation.ChatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatUserMessage.chat"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChatUserMessageUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChatUserMessageUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChatUserMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatusermessage.Table, chatusermessage.Columns, sqlgraph.NewFieldSpec(chatusermessage.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(chatusermessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(chatusermessage.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.StageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chatusermessage.StageTable,
			Columns: []string{chatusermessage.StageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chatusermessage.StageTable,
			Columns: []string{chatusermessage.StageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatusermessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatUserMessageUpdateOne is the builder for updating a single ChatUserMessage entity.
type ChatUserMessageUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ChatUserMessageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetContent sets the "content" field.
func (_u *ChatUserMessageUpdateOne) SetContent(v string) *ChatUserMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChatUserMessageUpdateOne) SetNillableContent(v *string) *ChatUserMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetAuthor sets the "author" field.
func (_u *ChatUserMessageUpdateOne) SetAuthor(v string) *ChatUserMessageUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *ChatUserMessageUpdateOne) SetNillableAuthor(v *string) *ChatUserMessageUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// SetStageID sets the "stage" edge to the Stage entity by ID.
func (_u *ChatUserMessageUpdateOne) SetStageID(id string) *ChatUserMessageUpdateOne {
	_u.mutation.SetStageID(id)
	return _u
}

// SetNillableStageID sets the "stage" edge to the Stage entity by ID if the given value is not nil.
func (_u *ChatUserMessageUpdateOne) SetNillableStageID(id *string) *ChatUserMessageUpdateOne {
	if id != nil {
		_u = _u.SetStageID(*id)
	}
	return _u
}

// SetStage sets the "stage" edge to the Stage entity.
func (_u *ChatUserMessageUpdateOne) SetStage(v *Stage) *ChatUserMessageUpdateOne {
	return _u.SetStageID(v.ID)
}

// Mutation returns the ChatUserMessageMutation object of the builder.
func (_u *ChatUserMessageUpdateOne) Mutation() *ChatUserMessageMutation {
	return _u.mutation
}

// ClearStage clears the "stage" edge to the Stage entity.
func (_u *ChatUserMessageUpdateOne) ClearStage() *ChatUserMessageUpdateOne {
	_u.mutation.ClearStage()
	return _u
}

// Where appends a list predicates to the ChatUserMessageUpdate builder.
func (_u *ChatUserMessageUpdateOne) Where(ps ...predicate.ChatUserMessage) *ChatUserMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatUserMessageUpdateOne) Select(field string, fields ...string) *ChatUserMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatUserMessage entity.
func (_u *ChatUserMessageUpdateOne) Save(ctx context.Context) (*ChatUserMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatUserMessageUpdateOne) SaveX(ctx context.Context) *ChatUserMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatUserMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatUserMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatUserMessageUpdateOne) check() error {
	if _u.mutation.ChatCleared() && len(_u.mutation.ChatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatUserMessage.chat"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChatUserMessageUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChatUserMessageUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChatUserMessageUpdateOne) sqlSave(ctx context.Context) (_node *ChatUserMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatusermessage.Table, chatusermessage.Columns, sqlgraph.NewFieldSpec(chatusermessage.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatUserMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatusermessage.FieldID)
		for _, f := range fields {
			if !chatusermessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatusermessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(chatusermessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(chatusermessage.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.StageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chatusermessage.StageTable,
			Columns: []string{chatusermessage.StageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   chatusermessage.StageTable,
			Columns: []string{chatusermessage.StageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ChatUserMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatusermessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
