// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/agentexecution"
	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/llminteraction"
	"github.com/codeready-toolchain/tarsy/ent/message"
	"github.com/codeready-toolchain/tarsy/ent/stage"
	"github.com/codeready-toolchain/tarsy/ent/timelineevent"
)

// LLMInteractionCreate is the builder for creating a LLMInteraction entity.
type LLMInteractionCreate struct {
	config
	mutation *LLMInteractionMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *LLMInteractionCreate) SetSessionID(v string) *LLMInteractionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetStageID sets the "stage_id" field.
func (_c *LLMInteractionCreate) SetStageID(v string) *LLMInteractionCreate {
	_c.mutation.SetStageID(v)
	return _c
}

// SetExecutionID sets the "execution_id" field.
func (_c *LLMInteractionCreate) SetExecutionID(v string) *LLMInteractionCreate {
	_c.mutation.SetExecutionID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LLMInteractionCreate) SetCreatedAt(v time.Time) *LLMInteractionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LLMInteractionCreate) SetNillableCreatedAt(v *time.Time) *LLMInteractionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetInteractionType sets the "interaction_type" field.
func (_c *LLMInteractionCreate) SetInteractionType(v llminteraction.InteractionType) *LLMInteractionCreate {
	_c.mutation.SetInteractionType(v)
	return _c
}

// SetModelName sets the "model_name" field.
func (_c *LLMInteractionCreate) SetModelName(v string) *LLMInteractionCreate {
	_c.mutation.SetModelName(v)
	return _c
}

// SetLastMessageID sets the "last_message_id" field.
func (_c *LLMInteractionCreate) SetLastMessageID(v string) *LLMInteractionCreate {
	_c.mutation.SetLastMessageID(v)
	return _c
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_c *LLMInteractionCreate) SetNillableLastMessageID(v *string) *LLMInteractionCreate {
	if v != nil {
		_c.SetLastMessageID(*v)
	}
	return _c
}

// SetLlmRequest sets the "llm_request" field.
func (_c *LLMInteractionCreate) SetLlmRequest(v map[string]interface{}) *LLMInteractionCreate {
	_c.mutation.SetLlmRequest(v)
	return _c
}

// SetLlmResponse sets the "llm_response" field.
func (_c *LLMInteractionCreate) SetLlmResponse(v map[string]interface{}) *LLMInteractionCreate {
	_c.mutation.SetLlmResponse(v)
	return _c
}

// SetThinkingContent sets the "thinking_content" field.
func (_c *LLMInteractionCreate) SetThinkingContent(v string) *LLMInteractionCreate {
	_c.mutation.SetThinkingContent(v)
	return _c
}

// SetNillableThinkingContent sets the "thinking_content" field if the given value is not nil.
func (_c *LLMInteractionCreate) SetNillableThinkingContent(v *string) *LLMInteractionCreate {
	if v != nil {
		_c.SetThinkingContent(*v)
	}
	return _c
}

// SetResponseMetadata sets the "response_metadata" field.
func (_c *LLMInteractionCreate) SetResponseMetadata(v map[string]interface{}) *LLMInteractionCreate {
	_c.mutation.SetResponseMetadata(v)
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *LLMInteractionCreate) SetInputTokens(v int) *LLMInteractionCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *LLMInteractionCreate) SetNillableInputTokens(v *int) *LLMInteractionCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *LLMInteractionCreate) SetOutputTokens(v int) *LLMInteractionCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *LLMInteractionCreate) SetNillableOutputTokens(v *int) *LLMInteractionCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetTotalTokens sets the "total_tokens" field.
func (_c *LLMInteractionCreate) SetTotalTokens(v int) *LLMInteractionCreate {
	_c.mutation.SetTotalTokens(v)
	return _c
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_c *LLMInteractionCreate) SetNillableTotalTokens(v *int) *LLMInteractionCreate {
	if v != nil {
		_c.SetTotalTokens(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *LLMInteractionCreate) SetDurationMs(v int) *LLMInteractionCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *LLMInteractionCreate) SetNillableDurationMs(v *int) *LLMInteractionCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *LLMInteractionCreate) SetErrorMessage(v string) *LLMInteractionCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *LLMInteractionCreate) SetNillableErrorMessage(v *string) *LLMInteractionCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LLMInteractionCreate) SetID(v string) *LLMInteractionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSession sets the "session" edge to the AlertSession entity.
func (_c *LLMInteractionCreate) SetSession(v *AlertSession) *LLMInteractionCreate {
	return _c.SetSessionID(v.ID)
}

// SetStage sets the "stage" edge to the Stage entity.
func (_c *LLMInteractionCreate) SetStage(v *Stage) *LLMInteractionCreate {
	return _c.SetStageID(v.ID)
}

// SetAgentExecutionID sets the "agent_execution" edge to the AgentExecution entity by ID.
func (_c *LLMInteractionCreate) SetAgentExecutionID(id string) *LLMInteractionCreate {
	_c.mutation.SetAgentExecutionID(id)
	return _c
}

// SetAgentExecution sets the "agent_execution" edge to the AgentExecution entity.
func (_c *LLMInteractionCreate) SetAgentExecution(v *AgentExecution) *LLMInteractionCreate {
	return _c.SetAgentExecutionID(v.ID)
}

// SetLastMessage sets the "last_message" edge to the Message entity.
func (_c *LLMInteractionCreate) SetLastMessage(v *Message) *LLMInteractionCreate {
	return _c.SetLastMessageID(v.ID)
}

// AddTimelineEventIDs adds the "timeline_events" edge to the TimelineEvent entity by IDs.
func (_c *LLMInteractionCreate) AddTimelineEventIDs(ids ...string) *LLMInteractionCreate {
	_c.mutation.AddTimelineEventIDs(ids...)
	return _c
}

// AddTimelineEvents adds the "timeline_events" edges to the TimelineEvent entity.
func (_c *LLMInteractionCreate) AddTimelineEvents(v ...*TimelineEvent) *LLMInteractionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTimelineEventIDs(ids...)
}

// Mutation returns the LLMInteractionMutation object of the builder.
func (_c *LLMInteractionCreate) Mutation() *LLMInteractionMutation {
	return _c.mutation
}

// Save creates the LLMInteraction in the database.
func (_c *LLMInteractionCreate) Save(ctx context.Context) (*LLMInteraction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LLMInteractionCreate) SaveX(ctx context.Context) *LLMInteraction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LLMInteractionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LLMInteractionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LLMInteractionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := llminteraction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LLMInteractionCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "LLMInteraction.session_id"`)}
	}
	if _, ok := _c.mutation.StageID(); !ok {
		return &ValidationError{Name: "stage_id", err: errors.New(`ent: missing required field "LLMInteraction.stage_id"`)}
	}
	if _, ok := _c.mutation.ExecutionID(); !ok {
		return &ValidationError{Name: "execution_id", err: errors.New(`ent: missing required field "LLMInteraction.execution_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LLMInteraction.created_at"`)}
	}
	if _, ok := _c.mutation.InteractionType(); !ok {
		return &ValidationError{Name: "interaction_type", err: errors.New(`ent: missing required field "LLMInteraction.interaction_type"`)}
	}
	if v, ok := _c.mutation.InteractionType(); ok {
		if err := llminteraction.InteractionTypeValidator(v); err != nil {
			return &ValidationError{Name: "interaction_type", err: fmt.Errorf(`ent: validator failed for field "LLMInteraction.interaction_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModelName(); !ok {
		return &ValidationError{Name: "model_name", err: errors.New(`ent: missing required field "LLMInteraction.model_name"`)}
	}
	if _, ok := _c.mutation.LlmRequest(); !ok {
		return &ValidationError{Name: "llm_request", err: errors.New(`ent: missing required field "LLMInteraction.llm_request"`)}
	}
	if _, ok := _c.mutation.LlmResponse(); !ok {
		return &ValidationError{Name: "llm_response", err: errors.New(`ent: missing required field "LLMInteraction.llm_response"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "LLMInteraction.session"`)}
	}
	if len(_c.mutation.StageIDs()) == 0 {
		return &ValidationError{Name: "stage", err: errors.New(`ent: missing required edge "LLMInteraction.stage"`)}
	}
	if len(_c.mutation.AgentExecutionIDs()) == 0 {
		return &ValidationError{Name: "agent_execution", err: errors.New(`ent: missing required edge "LLMInteraction.agent_execution"`)}
	}
	return nil
}

func (_c *LLMInteractionCreate) sqlSave(ctx context.Context) (*LLMInteraction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected LLMInteraction.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LLMInteractionCreate) createSpec() (*LLMInteraction, *sqlgraph.CreateSpec) {
	var (
		_node = &LLMInteraction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(llminteraction.Table, sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(llminteraction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.InteractionType(); ok {
		_spec.SetField(llminteraction.FieldInteractionType, field.TypeEnum, value)
		_node.InteractionType = value
	}
	if value, ok := _c.mutation.ModelName(); ok {
		_spec.SetField(llminteraction.FieldModelName, field.TypeString, value)
		_node.ModelName = value
	}
	if value, ok := _c.mutation.LlmRequest(); ok {
		_spec.SetField(llminteraction.FieldLlmRequest, field.TypeJSON, value)
		_node.LlmRequest = value
	}
	if value, ok := _c.mutation.LlmResponse(); ok {
		_spec.SetField(llminteraction.FieldLlmResponse, field.TypeJSON, value)
		_node.LlmResponse = value
	}
	if value, ok := _c.mutation.ThinkingContent(); ok {
		_spec.SetField(llminteraction.FieldThinkingContent, field.TypeString, value)
		_node.ThinkingContent = &value
	}
	if value, ok := _c.mutation.ResponseMetadata(); ok {
		_spec.SetField(llminteraction.FieldResponseMetadata, field.TypeJSON, value)
		_node.ResponseMetadata = value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(llminteraction.FieldInputTokens, field.TypeInt, value)
		_node.InputTokens = &value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(llminteraction.FieldOutputTokens, field.TypeInt, value)
		_node.OutputTokens = &value
	}
	if value, ok := _c.mutation.TotalTokens(); ok {
		_spec.SetField(llminteraction.FieldTotalTokens, field.TypeInt, value)
		_node.TotalTokens = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(llminteraction.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(llminteraction.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   llminteraction.SessionTable,
			Columns: []string{llminteraction.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertsession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   llminteraction.StageTable,
			Columns: []string{llminteraction.StageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   llminteraction.AgentExecutionTable,
			Columns: []string{llminteraction.AgentExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexecution.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ExecutionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LastMessageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   llminteraction.LastMessageTable,
			Columns: []string{llminteraction.LastMessageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LastMessageID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TimelineEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   llminteraction.TimelineEventsTable,
			Columns: []string{llminteraction.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LLMInteractionCreateBulk is the builder for creating many LLMInteraction entities in bulk.
type LLMInteractionCreateBulk struct {
	config
	err      error
	builders []*LLMInteractionCreate
}

// Save creates the LLMInteraction entities in the database.
func (_c *LLMInteractionCreateBulk) Save(ctx context.Context) ([]*LLMInteraction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LLMInteraction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LLMInteractionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LLMInteractionCreateBulk) SaveX(ctx context.Context) []*LLMInteraction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LLMInteractionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LLMInteractionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
