// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/mcpinteraction"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
	"github.com/codeready-toolchain/tarsy/ent/timelineevent"
)

// MCPInteractionUpdate is the builder for updating MCPInteraction entities.
type MCPInteractionUpdate struct {
	config
	hooks     []Hook
	mutation  *MCPInteractionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MCPInteractionUpdate builder.
func (_u *MCPInteractionUpdate) Where(ps ...predicate.MCPInteraction) *MCPInteractionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInteractionType sets the "interaction_type" field.
func (_u *MCPInteractionUpdate) SetInteractionType(v mcpinteraction.InteractionType) *MCPInteractionUpdate {
	_u.mutation.SetInteractionType(v)
	return _u
}

// SetNillableInteractionType sets the "interaction_type" field if the given value is not nil.
func (_u *MCPInteractionUpdate) SetNillableInteractionType(v *mcpinteraction.InteractionType) *MCPInteractionUpdate {
	if v != nil {
		_u.SetInteractionType(*v)
	}
	return _u
}

// SetServerName sets the "server_name" field.
func (_u *MCPInteractionUpdate) SetServerName(v string) *MCPInteractionUpdate {
	_u.mutation.SetServerName(v)
	return _u
}

// SetNillableServerName sets the "server_name" field if the given value is not nil.
func (_u *MCPInteractionUpdate) SetNillableServerName(v *string) *MCPInteractionUpdate {
	if v != nil {
		_u.SetServerName(*v)
	}
	return _u
}

// SetToolName sets the "tool_name" field.
func (_u *MCPInteractionUpdate) SetToolName(v string) *MCPInteractionUpdate {
	_u.mutation.SetToolName(v)
	return _u
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (_u *MCPInteractionUpdate) SetNillableToolName(v *string) *MCPInteractionUpdate {
	if v != nil {
		_u.SetToolName(*v)
	}
	return _u
}

// ClearToolName clears the value of the "tool_name" field.
func (_u *MCPInteractionUpdate) ClearToolName() *MCPInteractionUpdate {
	_u.mutation.ClearToolName()
	return _u
}

// SetToolArguments sets the "tool_arguments" field.
func (_u *MCPInteractionUpdate) SetToolArguments(v map[string]interface{}) *MCPInteractionUpdate {
	_u.mutation.SetToolArguments(v)
	return _u
}

// ClearToolArguments clears the value of the "tool_arguments" field.
func (_u *MCPInteractionUpdate) ClearToolArguments() *MCPInteractionUpdate {
	_u.mutation.ClearToolArguments()
	return _u
}

// SetToolResult sets the "tool_result" field.
func (_u *MCPInteractionUpdate) SetToolResult(v map[string]interface{}) *MCPInteractionUpdate {
	_u.mutation.SetToolResult(v)
	return _u
}

// ClearToolResult clears the value of the "tool_result" field.
func (_u *MCPInteractionUpdate) ClearToolResult() *MCPInteractionUpdate {
	_u.mutation.ClearToolResult()
	return _u
}

// SetAvailableTools sets the "available_tools" field.
func (_u *MCPInteractionUpdate) SetAvailableTools(v []interface{}) *MCPInteractionUpdate {
	_u.mutation.SetAvailableTools(v)
	return _u
}

// AppendAvailableTools appends value to the "available_tools" field.
func (_u *MCPInteractionUpdate) AppendAvailableTools(v []interface{}) *MCPInteractionUpdate {
	_u.mutation.AppendAvailableTools(v)
	return _u
}

// ClearAvailableTools clears the value of the "available_tools" field.
func (_u *MCPInteractionUpdate) ClearAvailableTools() *MCPInteractionUpdate {
	_u.mutation.ClearAvailableTools()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *MCPInteractionUpdate) SetDurationMs(v int) *MCPInteractionUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *MCPInteractionUpdate) SetNillableDurationMs(v *int) *MCPInteractionUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *MCPInteractionUpdate) AddDurationMs(v int) *MCPInteractionUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *MCPInteractionUpdate) ClearDurationMs() *MCPInteractionUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *MCPInteractionUpdate) SetErrorMessage(v string) *MCPInteractionUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *MCPInteractionUpdate) SetNillableErrorMessage(v *string) *MCPInteractionUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *MCPInteractionUpdate) ClearErrorMessage() *MCPInteractionUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// AddTimelineEventIDs adds the "timeline_events" edge to the TimelineEvent entity by IDs.
func (_u *MCPInteractionUpdate) AddTimelineEventIDs(ids ...string) *MCPInteractionUpdate {
	_u.mutation.AddTimelineEventIDs(ids...)
	return _u
}

// AddTimelineEvents adds the "timeline_events" edges to the TimelineEvent entity.
func (_u *MCPInteractionUpdate) AddTimelineEvents(v ...*TimelineEvent) *MCPInteractionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTimelineEventIDs(ids...)
}

// Mutation returns the MCPInteractionMutation object of the builder.
func (_u *MCPInteractionUpdate) Mutation() *MCPInteractionMutation {
	return _u.mutation
}

// ClearTimelineEvents clears all "timeline_events" edges to the TimelineEvent entity.
func (_u *MCPInteractionUpdate) ClearTimelineEvents() *MCPInteractionUpdate {
	_u.mutation.ClearTimelineEvents()
	return _u
}

// RemoveTimelineEventIDs removes the "timeline_events" edge to TimelineEvent entities by IDs.
func (_u *MCPInteractionUpdate) RemoveTimelineEventIDs(ids ...string) *MCPInteractionUpdate {
	_u.mutation.RemoveTimelineEventIDs(ids...)
	return _u
}

// RemoveTimelineEvents removes "timeline_events" edges to TimelineEvent entities.
func (_u *MCPInteractionUpdate) RemoveTimelineEvents(v ...*TimelineEvent) *MCPInteractionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTimelineEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MCPInteractionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MCPInteractionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MCPInteractionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MCPInteractionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MCPInteractionUpdate) check() error {
	if v, ok := _u.mutation.InteractionType(); ok {
		if err := mcpinteraction.InteractionTypeValidator(v); err != nil {
			return &ValidationError{Name: "interaction_type", err: fmt.Errorf(`ent: validator failed for field "MCPInteraction.interaction_type": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MCPInteraction.session"`)
	}
	if _u.mutation.StageCleared() && len(_u.mutation.StageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MCPInteraction.stage"`)
	}
	if _u.mutation.AgentExecutionCleared() && len(_u.mutation.AgentExecutionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MCPInteraction.agent_execution"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MCPInteractionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MCPInteractionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MCPInteractionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcpinteraction.Table, mcpinteraction.Columns, sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InteractionType(); ok {
		_spec.SetField(mcpinteraction.FieldInteractionType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ServerName(); ok {
		_spec.SetField(mcpinteraction.FieldServerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToolName(); ok {
		_spec.SetField(mcpinteraction.FieldToolName, field.TypeString, value)
	}
	if _u.mutation.ToolNameCleared() {
		_spec.ClearField(mcpinteraction.FieldToolName, field.TypeString)
	}
	if value, ok := _u.mutation.ToolArguments(); ok {
		_spec.SetField(mcpinteraction.FieldToolArguments, field.TypeJSON, value)
	}
	if _u.mutation.ToolArgumentsCleared() {
		_spec.ClearField(mcpinteraction.FieldToolArguments, field.TypeJSON)
	}
	if value, ok := _u.mutation.ToolResult(); ok {
		_spec.SetField(mcpinteraction.FieldToolResult, field.TypeJSON, value)
	}
	if _u.mutation.ToolResultCleared() {
		_spec.ClearField(mcpinteraction.FieldToolResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.AvailableTools(); ok {
		_spec.SetField(mcpinteraction.FieldAvailableTools, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAvailableTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mcpinteraction.FieldAvailableTools, value)
		})
	}
	if _u.mutation.AvailableToolsCleared() {
		_spec.ClearField(mcpinteraction.FieldAvailableTools, field.TypeJSON)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(mcpinteraction.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(mcpinteraction.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(mcpinteraction.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(mcpinteraction.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(mcpinteraction.FieldErrorMessage, field.TypeString)
	}
	if _u.mutation.TimelineEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpinteraction.TimelineEventsTable,
			Columns: []string{mcpinteraction.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTimelineEventsIDs(); len(nodes) > 0 && !_u.mutation.TimelineEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpinteraction.TimelineEventsTable,
			Columns: []string{mcpinteraction.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TimelineEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpinteraction.TimelineEventsTable,
			Columns: []string{mcpinteraction.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcpinteraction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MCPInteractionUpdateOne is the builder for updating a single MCPInteraction entity.
type MCPInteractionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MCPInteractionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetInteractionType sets the "interaction_type" field.
func (_u *MCPInteractionUpdateOne) SetInteractionType(v mcpinteraction.InteractionType) *MCPInteractionUpdateOne {
	_u.mutation.SetInteractionType(v)
	return _u
}

// SetNillableInteractionType sets the "interaction_type" field if the given value is not nil.
func (_u *MCPInteractionUpdateOne) SetNillableInteractionType(v *mcpinteraction.InteractionType) *MCPInteractionUpdateOne {
	if v != nil {
		_u.SetInteractionType(*v)
	}
	return _u
}

// SetServerName sets the "server_name" field.
func (_u *MCPInteractionUpdateOne) SetServerName(v string) *MCPInteractionUpdateOne {
	_u.mutation.SetServerName(v)
	return _u
}

// SetNillableServerName sets the "server_name" field if the given value is not nil.
func (_u *MCPInteractionUpdateOne) SetNillableServerName(v *string) *MCPInteractionUpdateOne {
	if v != nil {
		_u.SetServerName(*v)
	}
	return _u
}

// SetToolName sets the "tool_name" field.
func (_u *MCPInteractionUpdateOne) SetToolName(v string) *MCPInteractionUpdateOne {
	_u.mutation.SetToolName(v)
	return _u
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (_u *MCPInteractionUpdateOne) SetNillableToolName(v *string) *MCPInteractionUpdateOne {
	if v != nil {
		_u.SetToolName(*v)
	}
	return _u
}

// ClearToolName clears the value of the "tool_name" field.
func (_u *MCPInteractionUpdateOne) ClearToolName() *MCPInteractionUpdateOne {
	_u.mutation.ClearToolName()
	return _u
}

// SetToolArguments sets the "tool_arguments" field.
func (_u *MCPInteractionUpdateOne) SetToolArguments(v map[string]interface{}) *MCPInteractionUpdateOne {
	_u.mutation.SetToolArguments(v)
	return _u
}

// ClearToolArguments clears the value of the "tool_arguments" field.
func (_u *MCPInteractionUpdateOne) ClearToolArguments() *MCPInteractionUpdateOne {
	_u.mutation.ClearToolArguments()
	return _u
}

// SetToolResult sets the "tool_result" field.
func (_u *MCPInteractionUpdateOne) SetToolResult(v map[string]interface{}) *MCPInteractionUpdateOne {
	_u.mutation.SetToolResult(v)
	return _u
}

// ClearToolResult clears the value of the "tool_result" field.
func (_u *MCPInteractionUpdateOne) ClearToolResult() *MCPInteractionUpdateOne {
	_u.mutation.ClearToolResult()
	return _u
}

// SetAvailableTools sets the "available_tools" field.
func (_u *MCPInteractionUpdateOne) SetAvailableTools(v []interface{}) *MCPInteractionUpdateOne {
	_u.mutation.SetAvailableTools(v)
	return _u
}

// AppendAvailableTools appends value to the "available_tools" field.
func (_u *MCPInteractionUpdateOne) AppendAvailableTools(v []interface{}) *MCPInteractionUpdateOne {
	_u.mutation.AppendAvailableTools(v)
	return _u
}

// ClearAvailableTools clears the value of the "available_tools" field.
func (_u *MCPInteractionUpdateOne) ClearAvailableTools() *MCPInteractionUpdateOne {
	_u.mutation.ClearAvailableTools()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *MCPInteractionUpdateOne) SetDurationMs(v int) *MCPInteractionUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *MCPInteractionUpdateOne) SetNillableDurationMs(v *int) *MCPInteractionUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *MCPInteractionUpdateOne) AddDurationMs(v int) *MCPInteractionUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *MCPInteractionUpdateOne) ClearDurationMs() *MCPInteractionUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *MCPInteractionUpdateOne) SetErrorMessage(v string) *MCPInteractionUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *MCPInteractionUpdateOne) SetNillableErrorMessage(v *string) *MCPInteractionUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *MCPInteractionUpdateOne) ClearErrorMessage() *MCPInteractionUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// AddTimelineEventIDs adds the "timeline_events" edge to the TimelineEvent entity by IDs.
func (_u *MCPInteractionUpdateOne) AddTimelineEventIDs(ids ...string) *MCPInteractionUpdateOne {
	_u.mutation.AddTimelineEventIDs(ids...)
	return _u
}

// AddTimelineEvents adds the "timeline_events" edges to the TimelineEvent entity.
func (_u *MCPInteractionUpdateOne) AddTimelineEvents(v ...*TimelineEvent) *MCPInteractionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTimelineEventIDs(ids...)
}

// Mutation returns the MCPInteractionMutation object of the builder.
func (_u *MCPInteractionUpdateOne) Mutation() *MCPInteractionMutation {
	return _u.mutation
}

// ClearTimelineEvents clears all "timeline_events" edges to the TimelineEvent entity.
func (_u *MCPInteractionUpdateOne) ClearTimelineEvents() *MCPInteractionUpdateOne {
	_u.mutation.ClearTimelineEvents()
	return _u
}

// RemoveTimelineEventIDs removes the "timeline_events" edge to TimelineEvent entities by IDs.
func (_u *MCPInteractionUpdateOne) RemoveTimelineEventIDs(ids ...string) *MCPInteractionUpdateOne {
	_u.mutation.RemoveTimelineEventIDs(ids...)
	return _u
}

// RemoveTimelineEvents removes "timeline_events" edges to TimelineEvent entities.
func (_u *MCPInteractionUpdateOne) RemoveTimelineEvents(v ...*TimelineEvent) *MCPInteractionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTimelineEventIDs(ids...)
}

// Where appends a list predicates to the MCPInteractionUpdate builder.
func (_u *MCPInteractionUpdateOne) Where(ps ...predicate.MCPInteraction) *MCPInteractionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MCPInteractionUpdateOne) Select(field string, fields ...string) *MCPInteractionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MCPInteraction entity.
func (_u *MCPInteractionUpdateOne) Save(ctx context.Context) (*MCPInteraction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MCPInteractionUpdateOne) SaveX(ctx context.Context) *MCPInteraction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MCPInteractionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MCPInteractionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MCPInteractionUpdateOne) check() error {
	if v, ok := _u.mutation.InteractionType(); ok {
		if err := mcpinteraction.InteractionTypeValidator(v); err != nil {
			return &ValidationError{Name: "interaction_type", err: fmt.Errorf(`ent: validator failed for field "MCPInteraction.interaction_type": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MCPInteraction.session"`)
	}
	if _u.mutation.StageCleared() && len(_u.mutation.StageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MCPInteraction.stage"`)
	}
	if _u.mutation.AgentExecutionCleared() && len(_u.mutation.AgentExecutionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MCPInteraction.agent_execution"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MCPInteractionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MCPInteractionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MCPInteractionUpdateOne) sqlSave(ctx context.Context) (_node *MCPInteraction, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcpinteraction.Table, mcpinteraction.Columns, sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MCPInteraction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mcpinteraction.FieldID)
		for _, f := range fields {
			if !mcpinteraction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mcpinteraction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InteractionType(); ok {
		_spec.SetField(mcpinteraction.FieldInteractionType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ServerName(); ok {
		_spec.SetField(mcpinteraction.FieldServerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToolName(); ok {
		_spec.SetField(mcpinteraction.FieldToolName, field.TypeString, value)
	}
	if _u.mutation.ToolNameCleared() {
		_spec.ClearField(mcpinteraction.FieldToolName, field.TypeString)
	}
	if value, ok := _u.mutation.ToolArguments(); ok {
		_spec.SetField(mcpinteraction.FieldToolArguments, field.TypeJSON, value)
	}
	if _u.mutation.ToolArgumentsCleared() {
		_spec.ClearField(mcpinteraction.FieldToolArguments, field.TypeJSON)
	}
	if value, ok := _u.mutation.ToolResult(); ok {
		_spec.SetField(mcpinteraction.FieldToolResult, field.TypeJSON, value)
	}
	if _u.mutation.ToolResultCleared() {
		_spec.ClearField(mcpinteraction.FieldToolResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.AvailableTools(); ok {
		_spec.SetField(mcpinteraction.FieldAvailableTools, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAvailableTools(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mcpinteraction.FieldAvailableTools, value)
		})
	}
	if _u.mutation.AvailableToolsCleared() {
		_spec.ClearField(mcpinteraction.FieldAvailableTools, field.TypeJSON)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(mcpinteraction.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(mcpinteraction.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(mcpinteraction.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(mcpinteraction.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(mcpinteraction.FieldErrorMessage, field.TypeString)
	}
	if _u.mutation.TimelineEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpinteraction.TimelineEventsTable,
			Columns: []string{mcpinteraction.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTimelineEventsIDs(); len(nodes) > 0 && !_u.mutation.TimelineEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpinteraction.TimelineEventsTable,
			Columns: []string{mcpinteraction.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TimelineEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpinteraction.TimelineEventsTable,
			Columns: []string{mcpinteraction.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &MCPInteraction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcpinteraction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
