// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/agentexecution"
	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/mcpinteraction"
	"github.com/codeready-toolchain/tarsy/ent/stage"
	"github.com/codeready-toolchain/tarsy/ent/timelineevent"
)

// MCPInteractionCreate is the builder for creating a MCPInteraction entity.
type MCPInteractionCreate struct {
	config
	mutation *MCPInteractionMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *MCPInteractionCreate) SetSessionID(v string) *MCPInteractionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetStageID sets the "stage_id" field.
func (_c *MCPInteractionCreate) SetStageID(v string) *MCPInteractionCreate {
	_c.mutation.SetStageID(v)
	return _c
}

// SetExecutionID sets the "execution_id" field.
func (_c *MCPInteractionCreate) SetExecutionID(v string) *MCPInteractionCreate {
	_c.mutation.SetExecutionID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MCPInteractionCreate) SetCreatedAt(v time.Time) *MCPInteractionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MCPInteractionCreate) SetNillableCreatedAt(v *time.Time) *MCPInteractionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetInteractionType sets the "interaction_type" field.
func (_c *MCPInteractionCreate) SetInteractionType(v mcpinteraction.InteractionType) *MCPInteractionCreate {
	_c.mutation.SetInteractionType(v)
	return _c
}

// SetServerName sets the "server_name" field.
func (_c *MCPInteractionCreate) SetServerName(v string) *MCPInteractionCreate {
	_c.mutation.SetServerName(v)
	return _c
}

// SetToolName sets the "tool_name" field.
func (_c *MCPInteractionCreate) SetToolName(v string) *MCPInteractionCreate {
	_c.mutation.SetToolName(v)
	return _c
}

// SetNillableToolName sets the "tool_name" field if the given value is not nil.
func (_c *MCPInteractionCreate) SetNillableToolName(v *string) *MCPInteractionCreate {
	if v != nil {
		_c.SetToolName(*v)
	}
	return _c
}

// SetToolArguments sets the "tool_arguments" field.
func (_c *MCPInteractionCreate) SetToolArguments(v map[string]interface{}) *MCPInteractionCreate {
	_c.mutation.SetToolArguments(v)
	return _c
}

// SetToolResult sets the "tool_result" field.
func (_c *MCPInteractionCreate) SetToolResult(v map[string]interface{}) *MCPInteractionCreate {
	_c.mutation.SetToolResult(v)
	return _c
}

// SetAvailableTools sets the "available_tools" field.
func (_c *MCPInteractionCreate) SetAvailableTools(v []interface{}) *MCPInteractionCreate {
	_c.mutation.SetAvailableTools(v)
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *MCPInteractionCreate) SetDurationMs(v int) *MCPInteractionCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *MCPInteractionCreate) SetNillableDurationMs(v *int) *MCPInteractionCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *MCPInteractionCreate) SetErrorMessage(v string) *MCPInteractionCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *MCPInteractionCreate) SetNillableErrorMessage(v *string) *MCPInteractionCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MCPInteractionCreate) SetID(v string) *MCPInteractionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSession sets the "session" edge to the AlertSession entity.
func (_c *MCPInteractionCreate) SetSession(v *AlertSession) *MCPInteractionCreate {
	return _c.SetSessionID(v.ID)
}

// SetStage sets the "stage" edge to the Stage entity.
func (_c *MCPInteractionCreate) SetStage(v *Stage) *MCPInteractionCreate {
	return _c.SetStageID(v.ID)
}

// SetAgentExecutionID sets the "agent_execution" edge to the AgentExecution entity by ID.
func (_c *MCPInteractionCreate) SetAgentExecutionID(id string) *MCPInteractionCreate {
	_c.mutation.SetAgentExecutionID(id)
	return _c
}

// SetAgentExecution sets the "agent_execution" edge to the AgentExecution entity.
func (_c *MCPInteractionCreate) SetAgentExecution(v *AgentExecution) *MCPInteractionCreate {
	return _c.SetAgentExecutionID(v.ID)
}

// AddTimelineEventIDs adds the "timeline_events" edge to the TimelineEvent entity by IDs.
func (_c *MCPInteractionCreate) AddTimelineEventIDs(ids ...string) *MCPInteractionCreate {
	_c.mutation.AddTimelineEventIDs(ids...)
	return _c
}

// AddTimelineEvents adds the "timeline_events" edges to the TimelineEvent entity.
func (_c *MCPInteractionCreate) AddTimelineEvents(v ...*TimelineEvent) *MCPInteractionCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTimelineEventIDs(ids...)
}

// Mutation returns the MCPInteractionMutation object of the builder.
func (_c *MCPInteractionCreate) Mutation() *MCPInteractionMutation {
	return _c.mutation
}

// Save creates the MCPInteraction in the database.
func (_c *MCPInteractionCreate) Save(ctx context.Context) (*MCPInteraction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MCPInteractionCreate) SaveX(ctx context.Context) *MCPInteraction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MCPInteractionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MCPInteractionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MCPInteractionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mcpinteraction.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MCPInteractionCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "MCPInteraction.session_id"`)}
	}
	if _, ok := _c.mutation.StageID(); !ok {
		return &ValidationError{Name: "stage_id", err: errors.New(`ent: missing required field "MCPInteraction.stage_id"`)}
	}
	if _, ok := _c.mutation.ExecutionID(); !ok {
		return &ValidationError{Name: "execution_id", err: errors.New(`ent: missing required field "MCPInteraction.execution_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MCPInteraction.created_at"`)}
	}
	if _, ok := _c.mutation.InteractionType(); !ok {
		return &ValidationError{Name: "interaction_type", err: errors.New(`ent: missing required field "MCPInteraction.interaction_type"`)}
	}
	if v, ok := _c.mutation.InteractionType(); ok {
		if err := mcpinteraction.InteractionTypeValidator(v); err != nil {
			return &ValidationError{Name: "interaction_type", err: fmt.Errorf(`ent: validator failed for field "MCPInteraction.interaction_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ServerName(); !ok {
		return &ValidationError{Name: "server_name", err: errors.New(`ent: missing required field "MCPInteraction.server_name"`)}
	}
	if len(_c.mutation.SessionIDs()) == 0 {
		return &ValidationError{Name: "session", err: errors.New(`ent: missing required edge "MCPInteraction.session"`)}
	}
	if len(_c.mutation.StageIDs()) == 0 {
		return &ValidationError{Name: "stage", err: errors.New(`ent: missing required edge "MCPInteraction.stage"`)}
	}
	if len(_c.mutation.AgentExecutionIDs()) == 0 {
		return &ValidationError{Name: "agent_execution", err: errors.New(`ent: missing required edge "MCPInteraction.agent_execution"`)}
	}
	return nil
}

func (_c *MCPInteractionCreate) sqlSave(ctx context.Context) (*MCPInteraction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected MCPInteraction.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MCPInteractionCreate) createSpec() (*MCPInteraction, *sqlgraph.CreateSpec) {
	var (
		_node = &MCPInteraction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mcpinteraction.Table, sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mcpinteraction.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.InteractionType(); ok {
		_spec.SetField(mcpinteraction.FieldInteractionType, field.TypeEnum, value)
		_node.InteractionType = value
	}
	if value, ok := _c.mutation.ServerName(); ok {
		_spec.SetField(mcpinteraction.FieldServerName, field.TypeString, value)
		_node.ServerName = value
	}
	if value, ok := _c.mutation.ToolName(); ok {
		_spec.SetField(mcpinteraction.FieldToolName, field.TypeString, value)
		_node.ToolName = &value
	}
	if value, ok := _c.mutation.ToolArguments(); ok {
		_spec.SetField(mcpinteraction.FieldToolArguments, field.TypeJSON, value)
		_node.ToolArguments = value
	}
	if value, ok := _c.mutation.ToolResult(); ok {
		_spec.SetField(mcpinteraction.FieldToolResult, field.TypeJSON, value)
		_node.ToolResult = value
	}
	if value, ok := _c.mutation.AvailableTools(); ok {
		_spec.SetField(mcpinteraction.FieldAvailableTools, field.TypeJSON, value)
		_node.AvailableTools = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(mcpinteraction.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(mcpinteraction.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if nodes := _c.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mcpinteraction.SessionTable,
			Columns: []string{mcpinteraction.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertsession.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SessionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mcpinteraction.StageTable,
			Columns: []string{mcpinteraction.StageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mcpinteraction.AgentExecutionTable,
			Columns: []string{mcpinteraction.AgentExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexecution.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ExecutionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TimelineEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpinteraction.TimelineEventsTable,
			Columns: []string{mcpinteraction.TimelineEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MCPInteractionCreateBulk is the builder for creating many MCPInteraction entities in bulk.
type MCPInteractionCreateBulk struct {
	config
	err      error
	builders []*MCPInteractionCreate
}

// Save creates the MCPInteraction entities in the database.
func (_c *MCPInteractionCreateBulk) Save(ctx context.Context) ([]*MCPInteraction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MCPInteraction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MCPInteractionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MCPInteractionCreateBulk) SaveX(ctx context.Context) []*MCPInteraction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MCPInteractionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MCPInteractionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
