// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/sessionscore"
)

// SessionScore is the model entity for the SessionScore schema.
type SessionScore struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// SHA256 hex of judge prompts used
	PromptHash *string `json:"prompt_hash,omitempty"`
	// 0-100, extracted from LLM response
	TotalScore *int `json:"total_score,omitempty"`
	// ScoreAnalysis holds the value of the "score_analysis" field.
	ScoreAnalysis *string `json:"score_analysis,omitempty"`
	// MissingToolsAnalysis holds the value of the "missing_tools_analysis" field.
	MissingToolsAnalysis *string `json:"missing_tools_analysis,omitempty"`
	// Who triggered scoring (from extractAuthor)
	ScoreTriggeredBy string `json:"score_triggered_by,omitempty"`
	// Status holds the value of the "status" field.
	Status sessionscore.Status `json:"status,omitempty"`
	// When scoring was triggered
	StartedAt time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SessionScoreQuery when eager-loading is set.
	Edges        SessionScoreEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SessionScoreEdges holds the relations/edges for other nodes in the graph.
type SessionScoreEdges struct {
	// Session holds the value of the session edge.
	Session *AlertSession `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SessionScoreEdges) SessionOrErr() (*AlertSession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: alertsession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SessionScore) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sessionscore.FieldTotalScore:
			values[i] = new(sql.NullInt64)
		case sessionscore.FieldID, sessionscore.FieldSessionID, sessionscore.FieldPromptHash, sessionscore.FieldScoreAnalysis, sessionscore.FieldMissingToolsAnalysis, sessionscore.FieldScoreTriggeredBy, sessionscore.FieldStatus, sessionscore.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case sessionscore.FieldStartedAt, sessionscore.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SessionScore fields.
func (_m *SessionScore) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sessionscore.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case sessionscore.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case sessionscore.FieldPromptHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_hash", values[i])
			} else if value.Valid {
				_m.PromptHash = new(string)
				*_m.PromptHash = value.String
			}
		case sessionscore.FieldTotalScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_score", values[i])
			} else if value.Valid {
				_m.TotalScore = new(int)
				*_m.TotalScore = int(value.Int64)
			}
		case sessionscore.FieldScoreAnalysis:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field score_analysis", values[i])
			} else if value.Valid {
				_m.ScoreAnalysis = new(string)
				*_m.ScoreAnalysis = value.String
			}
		case sessionscore.FieldMissingToolsAnalysis:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field missing_tools_analysis", values[i])
			} else if value.Valid {
				_m.MissingToolsAnalysis = new(string)
				*_m.MissingToolsAnalysis = value.String
			}
		case sessionscore.FieldScoreTriggeredBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field score_triggered_by", values[i])
			} else if value.Valid {
				_m.ScoreTriggeredBy = value.String
			}
		case sessionscore.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = sessionscore.Status(value.String)
			}
		case sessionscore.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case sessionscore.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case sessionscore.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SessionScore.
// This includes values selected through modifiers, order, etc.
func (_m *SessionScore) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the SessionScore entity.
func (_m *SessionScore) QuerySession() *AlertSessionQuery {
	return NewSessionScoreClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this SessionScore.
// Note that you need to call SessionScore.Unwrap() before calling this method if this SessionScore
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SessionScore) Update() *SessionScoreUpdateOne {
	return NewSessionScoreClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SessionScore entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SessionScore) Unwrap() *SessionScore {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SessionScore is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SessionScore) String() string {
	var builder strings.Builder
	builder.WriteString("SessionScore(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	if v := _m.PromptHash; v != nil {
		builder.WriteString("prompt_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TotalScore; v != nil {
		builder.WriteString("total_score=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ScoreAnalysis; v != nil {
		builder.WriteString("score_analysis=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.MissingToolsAnalysis; v != nil {
		builder.WriteString("missing_tools_analysis=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("score_triggered_by=")
	builder.WriteString(_m.ScoreTriggeredBy)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// SessionScores is a parsable slice of SessionScore.
type SessionScores []*SessionScore
