// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/agentexecution"
	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/chat"
	"github.com/codeready-toolchain/tarsy/ent/chatusermessage"
	"github.com/codeready-toolchain/tarsy/ent/llminteraction"
	"github.com/codeready-toolchain/tarsy/ent/mcpinteraction"
	"github.com/codeready-toolchain/tarsy/ent/message"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
	"github.com/codeready-toolchain/tarsy/ent/stage"
	"github.com/codeready-toolchain/tarsy/ent/timelineevent"
)

// StageQuery is the builder for querying Stage entities.
type StageQuery struct {
	config
	ctx                 *QueryContext
	order               []stage.OrderOption
	inters              []Interceptor
	predicates          []predicate.Stage
	withSession         *AlertSessionQuery
	withAgentExecutions *AgentExecutionQuery
	withTimelineEvents  *TimelineEventQuery
	withMessages        *MessageQuery
	withLlmInteractions *LLMInteractionQuery
	withMcpInteractions *MCPInteractionQuery
	withChat            *ChatQuery
	withChatUserMessage *ChatUserMessageQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StageQuery builder.
func (_q *StageQuery) Where(ps ...predicate.Stage) *StageQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *StageQuery) Limit(limit int) *StageQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *StageQuery) Offset(offset int) *StageQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *StageQuery) Unique(unique bool) *StageQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *StageQuery) Order(o ...stage.OrderOption) *StageQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySession chains the current query on the "session" edge.
func (_q *StageQuery) QuerySession() *AlertSessionQuery {
	query := (&AlertSessionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stage.Table, stage.FieldID, selector),
			sqlgraph.To(alertsession.Table, alertsession.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stage.SessionTable, stage.SessionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAgentExecutions chains the current query on the "agent_executions" edge.
func (_q *StageQuery) QueryAgentExecutions() *AgentExecutionQuery {
	query := (&AgentExecutionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stage.Table, stage.FieldID, selector),
			sqlgraph.To(agentexecution.Table, agentexecution.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, stage.AgentExecutionsTable, stage.AgentExecutionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTimelineEvents chains the current query on the "timeline_events" edge.
func (_q *StageQuery) QueryTimelineEvents() *TimelineEventQuery {
	query := (&TimelineEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stage.Table, stage.FieldID, selector),
			sqlgraph.To(timelineevent.Table, timelineevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, stage.TimelineEventsTable, stage.TimelineEventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMessages chains the current query on the "messages" edge.
func (_q *StageQuery) QueryMessages() *MessageQuery {
	query := (&MessageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stage.Table, stage.FieldID, selector),
			sqlgraph.To(message.Table, message.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, stage.MessagesTable, stage.MessagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLlmInteractions chains the current query on the "llm_interactions" edge.
func (_q *StageQuery) QueryLlmInteractions() *LLMInteractionQuery {
	query := (&LLMInteractionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stage.Table, stage.FieldID, selector),
			sqlgraph.To(llminteraction.Table, llminteraction.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, stage.LlmInteractionsTable, stage.LlmInteractionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMcpInteractions chains the current query on the "mcp_interactions" edge.
func (_q *StageQuery) QueryMcpInteractions() *MCPInteractionQuery {
	query := (&MCPInteractionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stage.Table, stage.FieldID, selector),
			sqlgraph.To(mcpinteraction.Table, mcpinteraction.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, stage.McpInteractionsTable, stage.McpInteractionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChat chains the current query on the "chat" edge.
func (_q *StageQuery) QueryChat() *ChatQuery {
	query := (&ChatClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stage.Table, stage.FieldID, selector),
			sqlgraph.To(chat.Table, chat.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stage.ChatTable, stage.ChatColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChatUserMessage chains the current query on the "chat_user_message" edge.
func (_q *StageQuery) QueryChatUserMessage() *ChatUserMessageQuery {
	query := (&ChatUserMessageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stage.Table, stage.FieldID, selector),
			sqlgraph.To(chatusermessage.Table, chatusermessage.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, stage.ChatUserMessageTable, stage.ChatUserMessageColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Stage entity from the query.
// Returns a *NotFoundError when no Stage was found.
func (_q *StageQuery) First(ctx context.Context) (*Stage, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *StageQuery) FirstX(ctx context.Context) *Stage {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Stage ID from the query.
// Returns a *NotFoundError when no Stage ID was found.
func (_q *StageQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *StageQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Stage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Stage entity is found.
// Returns a *NotFoundError when no Stage entities are found.
func (_q *StageQuery) Only(ctx context.Context) (*Stage, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stage.Label}
	default:
		return nil, &NotSingularError{stage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *StageQuery) OnlyX(ctx context.Context) *Stage {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Stage ID in the query.
// Returns a *NotSingularError when more than one Stage ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *StageQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stage.Label}
	default:
		err = &NotSingularError{stage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *StageQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Stages.
func (_q *StageQuery) All(ctx context.Context) ([]*Stage, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Stage, *StageQuery]()
	return withInterceptors[[]*Stage](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *StageQuery) AllX(ctx context.Context) []*Stage {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Stage IDs.
func (_q *StageQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(stage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *StageQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *StageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*StageQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *StageQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *StageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *StageQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *StageQuery) Clone() *StageQuery {
	if _q == nil {
		return nil
	}
	return &StageQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]stage.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.Stage{}, _q.predicates...),
		withSession:         _q.withSession.Clone(),
		withAgentExecutions: _q.withAgentExecutions.Clone(),
		withTimelineEvents:  _q.withTimelineEvents.Clone(),
		withMessages:        _q.withMessages.Clone(),
		withLlmInteractions: _q.withLlmInteractions.Clone(),
		withMcpInteractions: _q.withMcpInteractions.Clone(),
		withChat:            _q.withChat.Clone(),
		withChatUserMessage: _q.withChatUserMessage.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSession tells the query-builder to eager-load the nodes that are connected to
// the "session" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StageQuery) WithSession(opts ...func(*AlertSessionQuery)) *StageQuery {
	query := (&AlertSessionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSession = query
	return _q
}

// WithAgentExecutions tells the query-builder to eager-load the nodes that are connected to
// the "agent_executions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StageQuery) WithAgentExecutions(opts ...func(*AgentExecutionQuery)) *StageQuery {
	query := (&AgentExecutionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAgentExecutions = query
	return _q
}

// WithTimelineEvents tells the query-builder to eager-load the nodes that are connected to
// the "timeline_events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StageQuery) WithTimelineEvents(opts ...func(*TimelineEventQuery)) *StageQuery {
	query := (&TimelineEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTimelineEvents = query
	return _q
}

// WithMessages tells the query-builder to eager-load the nodes that are connected to
// the "messages" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StageQuery) WithMessages(opts ...func(*MessageQuery)) *StageQuery {
	query := (&MessageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMessages = query
	return _q
}

// WithLlmInteractions tells the query-builder to eager-load the nodes that are connected to
// the "llm_interactions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StageQuery) WithLlmInteractions(opts ...func(*LLMInteractionQuery)) *StageQuery {
	query := (&LLMInteractionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLlmInteractions = query
	return _q
}

// WithMcpInteractions tells the query-builder to eager-load the nodes that are connected to
// the "mcp_interactions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StageQuery) WithMcpInteractions(opts ...func(*MCPInteractionQuery)) *StageQuery {
	query := (&MCPInteractionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMcpInteractions = query
	return _q
}

// WithChat tells the query-builder to eager-load the nodes that are connected to
// the "chat" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StageQuery) WithChat(opts ...func(*ChatQuery)) *StageQuery {
	query := (&ChatClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChat = query
	return _q
}

// WithChatUserMessage tells the query-builder to eager-load the nodes that are connected to
// the "chat_user_message" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StageQuery) WithChatUserMessage(opts ...func(*ChatUserMessageQuery)) *StageQuery {
	query := (&ChatUserMessageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChatUserMessage = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SessionID string `json:"session_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Stage.Query().
//		GroupBy(stage.FieldSessionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *StageQuery) GroupBy(field string, fields ...string) *StageGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StageGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = stage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SessionID string `json:"session_id,omitempty"`
//	}
//
//	client.Stage.Query().
//		Select(stage.FieldSessionID).
//		Scan(ctx, &v)
func (_q *StageQuery) Select(fields ...string) *StageSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &StageSelect{StageQuery: _q}
	sbuild.label = stage.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StageSelect configured with the given aggregations.
func (_q *StageQuery) Aggregate(fns ...AggregateFunc) *StageSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *StageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !stage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *StageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Stage, error) {
	var (
		nodes       = []*Stage{}
		_spec       = _q.querySpec()
		loadedTypes = [8]bool{
			_q.withSession != nil,
			_q.withAgentExecutions != nil,
			_q.withTimelineEvents != nil,
			_q.withMessages != nil,
			_q.withLlmInteractions != nil,
			_q.withMcpInteractions != nil,
			_q.withChat != nil,
			_q.withChatUserMessage != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Stage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Stage{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSession; query != nil {
		if err := _q.loadSession(ctx, query, nodes, nil,
			func(n *Stage, e *AlertSession) { n.Edges.Session = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAgentExecutions; query != nil {
		if err := _q.loadAgentExecutions(ctx, query, nodes,
			func(n *Stage) { n.Edges.AgentExecutions = []*AgentExecution{} },
			func(n *Stage, e *AgentExecution) { n.Edges.AgentExecutions = append(n.Edges.AgentExecutions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTimelineEvents; query != nil {
		if err := _q.loadTimelineEvents(ctx, query, nodes,
			func(n *Stage) { n.Edges.TimelineEvents = []*TimelineEvent{} },
			func(n *Stage, e *TimelineEvent) { n.Edges.TimelineEvents = append(n.Edges.TimelineEvents, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMessages; query != nil {
		if err := _q.loadMessages(ctx, query, nodes,
			func(n *Stage) { n.Edges.Messages = []*Message{} },
			func(n *Stage, e *Message) { n.Edges.Messages = append(n.Edges.Messages, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLlmInteractions; query != nil {
		if err := _q.loadLlmInteractions(ctx, query, nodes,
			func(n *Stage) { n.Edges.LlmInteractions = []*LLMInteraction{} },
			func(n *Stage, e *LLMInteraction) { n.Edges.LlmInteractions = append(n.Edges.LlmInteractions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMcpInteractions; query != nil {
		if err := _q.loadMcpInteractions(ctx, query, nodes,
			func(n *Stage) { n.Edges.McpInteractions = []*MCPInteraction{} },
			func(n *Stage, e *MCPInteraction) { n.Edges.McpInteractions = append(n.Edges.McpInteractions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChat; query != nil {
		if err := _q.loadChat(ctx, query, nodes, nil,
			func(n *Stage, e *Chat) { n.Edges.Chat = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChatUserMessage; query != nil {
		if err := _q.loadChatUserMessage(ctx, query, nodes, nil,
			func(n *Stage, e *ChatUserMessage) { n.Edges.ChatUserMessage = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *StageQuery) loadSession(ctx context.Context, query *AlertSessionQuery, nodes []*Stage, init func(*Stage), assign func(*Stage, *AlertSession)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Stage)
	for i := range nodes {
		fk := nodes[i].SessionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(alertsession.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "session_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *StageQuery) loadAgentExecutions(ctx context.Context, query *AgentExecutionQuery, nodes []*Stage, init func(*Stage), assign func(*Stage, *AgentExecution)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Stage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(agentexecution.FieldStageID)
	}
	query.Where(predicate.AgentExecution(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(stage.AgentExecutionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StageID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "stage_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *StageQuery) loadTimelineEvents(ctx context.Context, query *TimelineEventQuery, nodes []*Stage, init func(*Stage), assign func(*Stage, *TimelineEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Stage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(timelineevent.FieldStageID)
	}
	query.Where(predicate.TimelineEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(stage.TimelineEventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StageID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "stage_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *StageQuery) loadMessages(ctx context.Context, query *MessageQuery, nodes []*Stage, init func(*Stage), assign func(*Stage, *Message)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Stage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(message.FieldStageID)
	}
	query.Where(predicate.Message(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(stage.MessagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StageID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "stage_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *StageQuery) loadLlmInteractions(ctx context.Context, query *LLMInteractionQuery, nodes []*Stage, init func(*Stage), assign func(*Stage, *LLMInteraction)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Stage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(llminteraction.FieldStageID)
	}
	query.Where(predicate.LLMInteraction(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(stage.LlmInteractionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StageID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "stage_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *StageQuery) loadMcpInteractions(ctx context.Context, query *MCPInteractionQuery, nodes []*Stage, init func(*Stage), assign func(*Stage, *MCPInteraction)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Stage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(mcpinteraction.FieldStageID)
	}
	query.Where(predicate.MCPInteraction(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(stage.McpInteractionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StageID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "stage_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *StageQuery) loadChat(ctx context.Context, query *ChatQuery, nodes []*Stage, init func(*Stage), assign func(*Stage, *Chat)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Stage)
	for i := range nodes {
		if nodes[i].ChatID == nil {
			continue
		}
		fk := *nodes[i].ChatID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chat.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "chat_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *StageQuery) loadChatUserMessage(ctx context.Context, query *ChatUserMessageQuery, nodes []*Stage, init func(*Stage), assign func(*Stage, *ChatUserMessage)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Stage)
	for i := range nodes {
		if nodes[i].ChatUserMessageID == nil {
			continue
		}
		fk := *nodes[i].ChatUserMessageID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chatusermessage.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "chat_user_message_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *StageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *StageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(stage.Table, stage.Columns, sqlgraph.NewFieldSpec(stage.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stage.FieldID)
		for i := range fields {
			if fields[i] != stage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withSession != nil {
			_spec.Node.AddColumnOnce(stage.FieldSessionID)
		}
		if _q.withChat != nil {
			_spec.Node.AddColumnOnce(stage.FieldChatID)
		}
		if _q.withChatUserMessage != nil {
			_spec.Node.AddColumnOnce(stage.FieldChatUserMessageID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *StageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(stage.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = stage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StageGroupBy is the group-by builder for Stage entities.
type StageGroupBy struct {
	selector
	build *StageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *StageGroupBy) Aggregate(fns ...AggregateFunc) *StageGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *StageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StageQuery, *StageGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *StageGroupBy) sqlScan(ctx context.Context, root *StageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StageSelect is the builder for selecting fields of Stage entities.
type StageSelect struct {
	*StageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *StageSelect) Aggregate(fns ...AggregateFunc) *StageSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *StageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StageQuery, *StageSelect](ctx, _s.StageQuery, _s, _s.inters, v)
}

func (_s *StageSelect) sqlScan(ctx context.Context, root *StageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
