// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/codeready-toolchain/tarsy/ent/agentexecution"
	"github.com/codeready-toolchain/tarsy/ent/alertsession"
	"github.com/codeready-toolchain/tarsy/ent/llminteraction"
	"github.com/codeready-toolchain/tarsy/ent/mcpinteraction"
	"github.com/codeready-toolchain/tarsy/ent/stage"
	"github.com/codeready-toolchain/tarsy/ent/timelineevent"
)

// TimelineEvent is the model entity for the TimelineEvent schema.
type TimelineEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// Stage grouping — nil for session-level events (e.g. executive_summary)
	StageID *string `json:"stage_id,omitempty"`
	// Which agent — nil for session-level events (e.g. executive_summary)
	ExecutionID *string `json:"execution_id,omitempty"`
	// Order in timeline
	SequenceNumber int `json:"sequence_number,omitempty"`
	// Creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Last update (for streaming)
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType timelineevent.EventType `json:"event_type,omitempty"`
	// Status holds the value of the "status" field.
	Status timelineevent.Status `json:"status,omitempty"`
	// Event content (grows during streaming, updateable on completion)
	Content string `json:"content,omitempty"`
	// Type-specific data (tool_name, server_name, etc.)
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Link to trace details
	LlmInteractionID *string `json:"llm_interaction_id,omitempty"`
	// Link to trace details
	McpInteractionID *string `json:"mcp_interaction_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TimelineEventQuery when eager-loading is set.
	Edges        TimelineEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TimelineEventEdges holds the relations/edges for other nodes in the graph.
type TimelineEventEdges struct {
	// Session holds the value of the session edge.
	Session *AlertSession `json:"session,omitempty"`
	// Stage holds the value of the stage edge.
	Stage *Stage `json:"stage,omitempty"`
	// AgentExecution holds the value of the agent_execution edge.
	AgentExecution *AgentExecution `json:"agent_execution,omitempty"`
	// LlmInteraction holds the value of the llm_interaction edge.
	LlmInteraction *LLMInteraction `json:"llm_interaction,omitempty"`
	// McpInteraction holds the value of the mcp_interaction edge.
	McpInteraction *MCPInteraction `json:"mcp_interaction,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TimelineEventEdges) SessionOrErr() (*AlertSession, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: alertsession.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// StageOrErr returns the Stage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TimelineEventEdges) StageOrErr() (*Stage, error) {
	if e.Stage != nil {
		return e.Stage, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: stage.Label}
	}
	return nil, &NotLoadedError{edge: "stage"}
}

// AgentExecutionOrErr returns the AgentExecution value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TimelineEventEdges) AgentExecutionOrErr() (*AgentExecution, error) {
	if e.AgentExecution != nil {
		return e.AgentExecution, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: agentexecution.Label}
	}
	return nil, &NotLoadedError{edge: "agent_execution"}
}

// LlmInteractionOrErr returns the LlmInteraction value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TimelineEventEdges) LlmInteractionOrErr() (*LLMInteraction, error) {
	if e.LlmInteraction != nil {
		return e.LlmInteraction, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: llminteraction.Label}
	}
	return nil, &NotLoadedError{edge: "llm_interaction"}
}

// McpInteractionOrErr returns the McpInteraction value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TimelineEventEdges) McpInteractionOrErr() (*MCPInteraction, error) {
	if e.McpInteraction != nil {
		return e.McpInteraction, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: mcpinteraction.Label}
	}
	return nil, &NotLoadedError{edge: "mcp_interaction"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TimelineEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case timelineevent.FieldMetadata:
			values[i] = new([]byte)
		case timelineevent.FieldSequenceNumber:
			values[i] = new(sql.NullInt64)
		case timelineevent.FieldID, timelineevent.FieldSessionID, timelineevent.FieldStageID, timelineevent.FieldExecutionID, timelineevent.FieldEventType, timelineevent.FieldStatus, timelineevent.FieldContent, timelineevent.FieldLlmInteractionID, timelineevent.FieldMcpInteractionID:
			values[i] = new(sql.NullString)
		case timelineevent.FieldCreatedAt, timelineevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TimelineEvent fields.
func (_m *TimelineEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case timelineevent.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case timelineevent.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case timelineevent.FieldStageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stage_id", values[i])
			} else if value.Valid {
				_m.StageID = new(string)
				*_m.StageID = value.String
			}
		case timelineevent.FieldExecutionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_id", values[i])
			} else if value.Valid {
				_m.ExecutionID = new(string)
				*_m.ExecutionID = value.String
			}
		case timelineevent.FieldSequenceNumber:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sequence_number", values[i])
			} else if value.Valid {
				_m.SequenceNumber = int(value.Int64)
			}
		case timelineevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case timelineevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case timelineevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = timelineevent.EventType(value.String)
			}
		case timelineevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = timelineevent.Status(value.String)
			}
		case timelineevent.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case timelineevent.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case timelineevent.FieldLlmInteractionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field llm_interaction_id", values[i])
			} else if value.Valid {
				_m.LlmInteractionID = new(string)
				*_m.LlmInteractionID = value.String
			}
		case timelineevent.FieldMcpInteractionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mcp_interaction_id", values[i])
			} else if value.Valid {
				_m.McpInteractionID = new(string)
				*_m.McpInteractionID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TimelineEvent.
// This includes values selected through modifiers, order, etc.
func (_m *TimelineEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the TimelineEvent entity.
func (_m *TimelineEvent) QuerySession() *AlertSessionQuery {
	return NewTimelineEventClient(_m.config).QuerySession(_m)
}

// QueryStage queries the "stage" edge of the TimelineEvent entity.
func (_m *TimelineEvent) QueryStage() *StageQuery {
	return NewTimelineEventClient(_m.config).QueryStage(_m)
}

// QueryAgentExecution queries the "agent_execution" edge of the TimelineEvent entity.
func (_m *TimelineEvent) QueryAgentExecution() *AgentExecutionQuery {
	return NewTimelineEventClient(_m.config).QueryAgentExecution(_m)
}

// QueryLlmInteraction queries the "llm_interaction" edge of the TimelineEvent entity.
func (_m *TimelineEvent) QueryLlmInteraction() *LLMInteractionQuery {
	return NewTimelineEventClient(_m.config).QueryLlmInteraction(_m)
}

// QueryMcpInteraction queries the "mcp_interaction" edge of the TimelineEvent entity.
func (_m *TimelineEvent) QueryMcpInteraction() *MCPInteractionQuery {
	return NewTimelineEventClient(_m.config).QueryMcpInteraction(_m)
}

// Update returns a builder for updating this TimelineEvent.
// Note that you need to call TimelineEvent.Unwrap() before calling this method if this TimelineEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TimelineEvent) Update() *TimelineEventUpdateOne {
	return NewTimelineEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TimelineEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TimelineEvent) Unwrap() *TimelineEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TimelineEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TimelineEvent) String() string {
	var builder strings.Builder
	builder.WriteString("TimelineEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	if v := _m.StageID; v != nil {
		builder.WriteString("stage_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExecutionID; v != nil {
		builder.WriteString("execution_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("sequence_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.SequenceNumber))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.LlmInteractionID; v != nil {
		builder.WriteString("llm_interaction_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.McpInteractionID; v != nil {
		builder.WriteString("mcp_interaction_id=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// TimelineEvents is a parsable slice of TimelineEvent.
type TimelineEvents []*TimelineEvent
