// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codeready-toolchain/tarsy/ent/llminteraction"
	"github.com/codeready-toolchain/tarsy/ent/mcpinteraction"
	"github.com/codeready-toolchain/tarsy/ent/predicate"
	"github.com/codeready-toolchain/tarsy/ent/timelineevent"
)

// TimelineEventUpdate is the builder for updating TimelineEvent entities.
type TimelineEventUpdate struct {
	config
	hooks     []Hook
	mutation  *TimelineEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TimelineEventUpdate builder.
func (_u *TimelineEventUpdate) Where(ps ...predicate.TimelineEvent) *TimelineEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSequenceNumber sets the "sequence_number" field.
func (_u *TimelineEventUpdate) SetSequenceNumber(v int) *TimelineEventUpdate {
	_u.mutation.ResetSequenceNumber()
	_u.mutation.SetSequenceNumber(v)
	return _u
}

// SetNillableSequenceNumber sets the "sequence_number" field if the given value is not nil.
func (_u *TimelineEventUpdate) SetNillableSequenceNumber(v *int) *TimelineEventUpdate {
	if v != nil {
		_u.SetSequenceNumber(*v)
	}
	return _u
}

// AddSequenceNumber adds value to the "sequence_number" field.
func (_u *TimelineEventUpdate) AddSequenceNumber(v int) *TimelineEventUpdate {
	_u.mutation.AddSequenceNumber(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TimelineEventUpdate) SetUpdatedAt(v time.Time) *TimelineEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *TimelineEventUpdate) SetEventType(v timelineevent.EventType) *TimelineEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *TimelineEventUpdate) SetNillableEventType(v *timelineevent.EventType) *TimelineEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TimelineEventUpdate) SetStatus(v timelineevent.Status) *TimelineEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TimelineEventUpdate) SetNillableStatus(v *timelineevent.Status) *TimelineEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *TimelineEventUpdate) SetContent(v string) *TimelineEventUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *TimelineEventUpdate) SetNillableContent(v *string) *TimelineEventUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TimelineEventUpdate) SetMetadata(v map[string]interface{}) *TimelineEventUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *TimelineEventUpdate) ClearMetadata() *TimelineEventUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetLlmInteractionID sets the "llm_interaction_id" field.
func (_u *TimelineEventUpdate) SetLlmInteractionID(v string) *TimelineEventUpdate {
	_u.mutation.SetLlmInteractionID(v)
	return _u
}

// SetNillableLlmInteractionID sets the "llm_interaction_id" field if the given value is not nil.
func (_u *TimelineEventUpdate) SetNillableLlmInteractionID(v *string) *TimelineEventUpdate {
	if v != nil {
		_u.SetLlmInteractionID(*v)
	}
	return _u
}

// ClearLlmInteractionID clears the value of the "llm_interaction_id" field.
func (_u *TimelineEventUpdate) ClearLlmInteractionID() *TimelineEventUpdate {
	_u.mutation.ClearLlmInteractionID()
	return _u
}

// SetMcpInteractionID sets the "mcp_interaction_id" field.
func (_u *TimelineEventUpdate) SetMcpInteractionID(v string) *TimelineEventUpdate {
	_u.mutation.SetMcpInteractionID(v)
	return _u
}

// SetNillableMcpInteractionID sets the "mcp_interaction_id" field if the given value is not nil.
func (_u *TimelineEventUpdate) SetNillableMcpInteractionID(v *string) *TimelineEventUpdate {
	if v != nil {
		_u.SetMcpInteractionID(*v)
	}
	return _u
}

// ClearMcpInteractionID clears the value of the "mcp_interaction_id" field.
func (_u *TimelineEventUpdate) ClearMcpInteractionID() *TimelineEventUpdate {
	_u.mutation.ClearMcpInteractionID()
	return _u
}

// SetLlmInteraction sets the "llm_interaction" edge to the LLMInteraction entity.
func (_u *TimelineEventUpdate) SetLlmInteraction(v *LLMInteraction) *TimelineEventUpdate {
	return _u.SetLlmInteractionID(v.ID)
}

// SetMcpInteraction sets the "mcp_interaction" edge to the MCPInteraction entity.
func (_u *TimelineEventUpdate) SetMcpInteraction(v *MCPInteraction) *TimelineEventUpdate {
	return _u.SetMcpInteractionID(v.ID)
}

// Mutation returns the TimelineEventMutation object of the builder.
func (_u *TimelineEventUpdate) Mutation() *TimelineEventMutation {
	return _u.mutation
}

// ClearLlmInteraction clears the "llm_interaction" edge to the LLMInteraction entity.
func (_u *TimelineEventUpdate) ClearLlmInteraction() *TimelineEventUpdate {
	_u.mutation.ClearLlmInteraction()
	return _u
}

// ClearMcpInteraction clears the "mcp_interaction" edge to the MCPInteraction entity.
func (_u *TimelineEventUpdate) ClearMcpInteraction() *TimelineEventUpdate {
	_u.mutation.ClearMcpInteraction()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TimelineEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TimelineEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TimelineEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TimelineEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TimelineEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := timelineevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TimelineEventUpdate) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := timelineevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "TimelineEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := timelineevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TimelineEvent.status": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TimelineEvent.session"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TimelineEventUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TimelineEventUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TimelineEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(timelineevent.Table, timelineevent.Columns, sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SequenceNumber(); ok {
		_spec.SetField(timelineevent.FieldSequenceNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSequenceNumber(); ok {
		_spec.AddField(timelineevent.FieldSequenceNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(timelineevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(timelineevent.FieldEventType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(timelineevent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(timelineevent.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(timelineevent.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(timelineevent.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.LlmInteractionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timelineevent.LlmInteractionTable,
			Columns: []string{timelineevent.LlmInteractionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LlmInteractionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timelineevent.LlmInteractionTable,
			Columns: []string{timelineevent.LlmInteractionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.McpInteractionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timelineevent.McpInteractionTable,
			Columns: []string{timelineevent.McpInteractionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.McpInteractionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timelineevent.McpInteractionTable,
			Columns: []string{timelineevent.McpInteractionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{timelineevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TimelineEventUpdateOne is the builder for updating a single TimelineEvent entity.
type TimelineEventUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TimelineEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetSequenceNumber sets the "sequence_number" field.
func (_u *TimelineEventUpdateOne) SetSequenceNumber(v int) *TimelineEventUpdateOne {
	_u.mutation.ResetSequenceNumber()
	_u.mutation.SetSequenceNumber(v)
	return _u
}

// SetNillableSequenceNumber sets the "sequence_number" field if the given value is not nil.
func (_u *TimelineEventUpdateOne) SetNillableSequenceNumber(v *int) *TimelineEventUpdateOne {
	if v != nil {
		_u.SetSequenceNumber(*v)
	}
	return _u
}

// AddSequenceNumber adds value to the "sequence_number" field.
func (_u *TimelineEventUpdateOne) AddSequenceNumber(v int) *TimelineEventUpdateOne {
	_u.mutation.AddSequenceNumber(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TimelineEventUpdateOne) SetUpdatedAt(v time.Time) *TimelineEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *TimelineEventUpdateOne) SetEventType(v timelineevent.EventType) *TimelineEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *TimelineEventUpdateOne) SetNillableEventType(v *timelineevent.EventType) *TimelineEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TimelineEventUpdateOne) SetStatus(v timelineevent.Status) *TimelineEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TimelineEventUpdateOne) SetNillableStatus(v *timelineevent.Status) *TimelineEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *TimelineEventUpdateOne) SetContent(v string) *TimelineEventUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *TimelineEventUpdateOne) SetNillableContent(v *string) *TimelineEventUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TimelineEventUpdateOne) SetMetadata(v map[string]interface{}) *TimelineEventUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *TimelineEventUpdateOne) ClearMetadata() *TimelineEventUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetLlmInteractionID sets the "llm_interaction_id" field.
func (_u *TimelineEventUpdateOne) SetLlmInteractionID(v string) *TimelineEventUpdateOne {
	_u.mutation.SetLlmInteractionID(v)
	return _u
}

// SetNillableLlmInteractionID sets the "llm_interaction_id" field if the given value is not nil.
func (_u *TimelineEventUpdateOne) SetNillableLlmInteractionID(v *string) *TimelineEventUpdateOne {
	if v != nil {
		_u.SetLlmInteractionID(*v)
	}
	return _u
}

// ClearLlmInteractionID clears the value of the "llm_interaction_id" field.
func (_u *TimelineEventUpdateOne) ClearLlmInteractionID() *TimelineEventUpdateOne {
	_u.mutation.ClearLlmInteractionID()
	return _u
}

// SetMcpInteractionID sets the "mcp_interaction_id" field.
func (_u *TimelineEventUpdateOne) SetMcpInteractionID(v string) *TimelineEventUpdateOne {
	_u.mutation.SetMcpInteractionID(v)
	return _u
}

// SetNillableMcpInteractionID sets the "mcp_interaction_id" field if the given value is not nil.
func (_u *TimelineEventUpdateOne) SetNillableMcpInteractionID(v *string) *TimelineEventUpdateOne {
	if v != nil {
		_u.SetMcpInteractionID(*v)
	}
	return _u
}

// ClearMcpInteractionID clears the value of the "mcp_interaction_id" field.
func (_u *TimelineEventUpdateOne) ClearMcpInteractionID() *TimelineEventUpdateOne {
	_u.mutation.ClearMcpInteractionID()
	return _u
}

// SetLlmInteraction sets the "llm_interaction" edge to the LLMInteraction entity.
func (_u *TimelineEventUpdateOne) SetLlmInteraction(v *LLMInteraction) *TimelineEventUpdateOne {
	return _u.SetLlmInteractionID(v.ID)
}

// SetMcpInteraction sets the "mcp_interaction" edge to the MCPInteraction entity.
func (_u *TimelineEventUpdateOne) SetMcpInteraction(v *MCPInteraction) *TimelineEventUpdateOne {
	return _u.SetMcpInteractionID(v.ID)
}

// Mutation returns the TimelineEventMutation object of the builder.
func (_u *TimelineEventUpdateOne) Mutation() *TimelineEventMutation {
	return _u.mutation
}

// ClearLlmInteraction clears the "llm_interaction" edge to the LLMInteraction entity.
func (_u *TimelineEventUpdateOne) ClearLlmInteraction() *TimelineEventUpdateOne {
	_u.mutation.ClearLlmInteraction()
	return _u
}

// ClearMcpInteraction clears the "mcp_interaction" edge to the MCPInteraction entity.
func (_u *TimelineEventUpdateOne) ClearMcpInteraction() *TimelineEventUpdateOne {
	_u.mutation.ClearMcpInteraction()
	return _u
}

// Where appends a list predicates to the TimelineEventUpdate builder.
func (_u *TimelineEventUpdateOne) Where(ps ...predicate.TimelineEvent) *TimelineEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TimelineEventUpdateOne) Select(field string, fields ...string) *TimelineEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TimelineEvent entity.
func (_u *TimelineEventUpdateOne) Save(ctx context.Context) (*TimelineEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TimelineEventUpdateOne) SaveX(ctx context.Context) *TimelineEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TimelineEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TimelineEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TimelineEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := timelineevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TimelineEventUpdateOne) check() error {
	if v, ok := _u.mutation.EventType(); ok {
		if err := timelineevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "TimelineEvent.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := timelineevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TimelineEvent.status": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TimelineEvent.session"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TimelineEventUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TimelineEventUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TimelineEventUpdateOne) sqlSave(ctx context.Context) (_node *TimelineEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(timelineevent.Table, timelineevent.Columns, sqlgraph.NewFieldSpec(timelineevent.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TimelineEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, timelineevent.FieldID)
		for _, f := range fields {
			if !timelineevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != timelineevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SequenceNumber(); ok {
		_spec.SetField(timelineevent.FieldSequenceNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSequenceNumber(); ok {
		_spec.AddField(timelineevent.FieldSequenceNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(timelineevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(timelineevent.FieldEventType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(timelineevent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(timelineevent.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(timelineevent.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(timelineevent.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.LlmInteractionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timelineevent.LlmInteractionTable,
			Columns: []string{timelineevent.LlmInteractionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LlmInteractionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timelineevent.LlmInteractionTable,
			Columns: []string{timelineevent.LlmInteractionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(llminteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.McpInteractionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timelineevent.McpInteractionTable,
			Columns: []string{timelineevent.McpInteractionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.McpInteractionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timelineevent.McpInteractionTable,
			Columns: []string{timelineevent.McpInteractionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpinteraction.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TimelineEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{timelineevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
